### ISSUE TITLE
"Discarded unknown attribute" problem flagged on events

### ISSUE THREAD

**Issue by KevinKelchen** [getsentry/sentry-capacitor#125]
### Overview

Events in Sentry have a problem flagged that says `Discarded unknown attribute`.

On iOS the problem will be
- `sdkProcessingMetadata: Discarded unknown attribute`

On Android the problem will be
- `unknown: Discarded unknown attribute`

This occurs on hybrid iOS and hybrid Android which use the native SDKs to process and send the event (might be relevant). It is not an issue on Web wherein it works fine (it also works fine using `@sentry/browser` directly).

A repro can be found [here](https://github.com/KevinKelchen/sentry-capacitor-unknown-metadata-issue).

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Sentry Capacitor - 0.4.2

### Steps to Reproduce

See [Steps to Reproduce](https://github.com/KevinKelchen/sentry-capacitor-unknown-metadata-issue#steps-to-reproduce).

### Expected Result

The event from hybrid iOS and Android appears in Sentry without a problem being flagged.

We normally do not have problems flagged on our events from production builds. If the red problem banner were to be accepted as always appearing due to this issue, I think people would initially think something is really wrong. After being told to ignore it due to this issue, I think they then would start to ignore the problem banner altogether which would make it less likely for people to notice different, more actionable problems.

### Actual Result

The event from hybrid iOS and Android appears in Sentry with a problem being flagged.

### Final Thoughts

Thank you so much for taking the time to investigate and/or work on this issue! 😀

**Comment by lucas-zimerman** [comment]
It seems like both are related to the field called `sdkProcessingMetadata` we'll keep investigating on how to solve this, thanks for reporting this issue :D

**Comment by KevinKelchen** [comment]
Thank you for the fix! 😀
