### ISSUE TITLE
Native Errors: beforeSend callback not executed before sending event to server

### ISSUE THREAD

**Issue by BertoDBQ** [getsentry/sentry-capacitor#127]
### Overview

Native IOS errors (ie OutOfMemory) are not going thru the beforeSend callback event before being sent to the server.

Would like to use the beforeSend callback to filter out native errors and not log them to Sentry in development mode.  

Have been able to get around this by setting 'enableNative' equal to false.  Is there some equivalent to beforeSend for native errors that may be used?  (maybe this is a feature request vs bug???)    

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
Sentry Capacitor - 0.4.2

### Expected Result

Expected native errors to flow thru the beforeSend callback before being sent to Sentry.

**Comment by lucas-zimerman** [comment]
Native events can only be called from the Native before send and not from the JavaScript callback so you'll need to check the iOS layer to filter the native layers.

This is not a trivial change and won't be altered on Sentry Capacitor.
