### ISSUE TITLE
(Android) Breadcrumbs are getting duplicated

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-capacitor#136]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version? 0.4.2

### Steps to Reproduce
I just opened the sample app and there were duplicated breadcrumbs while using it.

![image](https://user-images.githubusercontent.com/8229322/155538817-790127b0-e453-4b7a-8791-f9a198a34950.png)

### Expected Result

events without duplicated breadcrumbs.

### Actual Result

breadcrumbs from JS side are duplicated
![image](https://user-images.githubusercontent.com/8229322/155539043-8d5961fc-7b4b-4d8e-bed2-fc5d5967b7dc.png)
![image](https://user-images.githubusercontent.com/8229322/155539157-4d197f83-e5cb-4255-b2ff-73099de7d161.png)

**Comment by hermitdemschoenenleben** [comment]
I see the same problem in production. For some reason, it doesn't seem to happen with all events and all devices, though

**Comment by bruno-garcia** [comment]
Happened on React Native: https://github.com/getsentry/sentry-react-native/issues/1409

Now I see that it seems like it happened again: https://github.com/getsentry/sentry-react-native/issues/1409

**Comment by lucas-zimerman** [comment]
Problem seems to be happening here
https://github.com/getsentry/sentry-java/blob/d1029084e146b5ff02b1359e8bdf0a7252ebf2e5/sentry/src/main/java/io/sentry/SentryClient.java#L76-L80This is returning true, triggering the breadcrumb duplication
