### ISSUE TITLE
Disabling the SDK still results in native errors being sent

### ISSUE THREAD

**Issue by KevinKelchen** [getsentry/sentry-capacitor#137]
### Overview

Disabling the SDK still results in native errors being sent.

There are 2 scenarios:
- Scenario 1 is that `enabled` and `enableNative` flags at initialization do not stop Android native errors from being sent.
- Scenario 2 is that disabling the SDK at runtime does not stop Android and iOS native errors from being sent.

This occurs on hybrid iOS and hybrid Android which use the native SDKs to process and send the event (might be relevant). It is not an issue on Web wherein it works fine (it also works fine using `@sentry/browser` directly).

A repro can be found [here](https://github.com/KevinKelchen/sentry-capacitor-enable-sdk-issue).

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Sentry Capacitor - 0.4.3

### Steps to Reproduce

See [Steps to Reproduce](https://github.com/KevinKelchen/sentry-capacitor-enable-sdk-issue#steps-to-reproduce).

### Expected Result

- Scenario 1
  - Expected setting `enabled: false` (and perhaps even `enableNative: false`) to be sufficient at stopping native errors from being sent on Android. `enabled: false` alone works as expected on iOS. `enabled: false` alone works as expected for Android *JavaScript* errors.
- Scenario 2
  - Expected setting `getCurrentHub().getClient().getOptions().enabled = false` (and perhaps even `(getCurrentHub().getClient().getOptions() as any).enableNative` with `(getCurrentHub().getClient().getOptions() as any).enableNativeCrashHandling)` at runtime to be sufficient at stopping native errors from being sent on Android and iOS.
  - Related: If we are to use `getCurrentHub().getClient().getOptions()` to disable the SDK at runtime, it would be nice if it had TypeScript typings that reflects the changes in the Capacitor SDK such as the additional native-related properties which do appear to be present at runtime.

### Actual Result

- Scenario 1
  - Setting `enabled: false` (even with `enableNative: false`) results in native errors being sent on Android.
- Scenario 2
  - Setting `getCurrentHub().getClient().getOptions().enabled = false` (even with `(getCurrentHub().getClient().getOptions() as any).enableNative` and `(getCurrentHub().getClient().getOptions() as any).enableNativeCrashHandling)` at runtime results in native errors being sent on Android and iOS.
  - Related: Using `getCurrentHub().getClient().getOptions()` to disable the SDK at runtime does not have TypeScript typings that reflects the changes in the Capacitor SDK such as the additional native-related properties which do appear to be present at runtime.

The TypeScript typings enhancement could be its own issue, but I erred on the side of including it in here for now in case there's a preference to keep all of this SDK enable/disable stuff in one place. Also, if there's a better approach for disabling the SDK at runtime that results in not using the untyped native-related properties of those APIs, then our use case for them may go away. 🙂

### Final Thoughts

Thank you so much for taking the time to investigate and/or work on this issue! 😀

**Comment by lucas-zimerman** [comment]
Hi Kevin,
Thank you for reporting this issue, we'll investigate it further and update this issue once a conclusion is made.

**Comment by KevinKelchen** [comment]
Hi @lucas-zimerman! 👋

Thank you very much for the fix! 😀

The fix definitely resolves "Scenario 1" described in the OP where setting the `enabled` flag to `false` at Sentry SDK initialization does not stop Android native errors from being sent. 🙂  No more unwanted events in that case!

"Scenario 2" still seems to behave the same as it did before. The issue behavior is indeed unexpected, but it's also something we can live with.

If there's interest in addressing Scenario 2 and you'd like a separate issue opened for it, I can certainly do that.

Thanks so much!

Take care,

Kevin
