### ISSUE TITLE
 IOS JS errors do not include native metadata -  Android does

### ISSUE THREAD

**Issue by BertoDBQ** [getsentry/sentry-capacitor#138]
### Overview

IOS Sentry JS errors do not include native metadata; Android does include native metadata.

A repro can be found  [here](https://github.com/BertoDBQ/sentry-capacitor-ios-native-metadata-issue).

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
Sentry Capacitor - 0.4.3

### Steps to Reproduce

See [Steps to Reproduce](https://github.com/BertoDBQ/sentry-capacitor-ios-native-metadata-issue#steps-to-reproduce)

### Expected Result

Expecting to see IOS native metadata on JS errors.   

### IOS Native-level error example:

<img width="814" alt="Screen Shot 2022-02-25 at 10 08 12 AM" src="https://user-images.githubusercontent.com/33296819/155748549-1a7b496f-c1f5-4b0e-b793-2cfeb5689e6d.png">

**Comment by jennmueng** [comment]
Yep, this is as we do not implement [fetchNativeDeviceContexts](https://github.com/getsentry/sentry-react-native/blob/6ac64ba08675b04226d43abe83b2ebe9ef2aab4f/src/js/wrapper.ts#L263-L277) like on the React Native SDK. The Sentry Android SDK adds the context to the events as they are processed, but the Cocoa SDK does not.

This is a feature up for grabs for someone to submit a PR for

**Comment by KevinKelchen** [comment]
I’ve been watching this issue and am really looking forward to this feature! 😀

Thanks so much, @lucas-zimerman! ❤️
