### ISSUE TITLE
[Documentation] Capacitor 3 - Use Automatic Android Plugin Loading

### ISSUE THREAD

**Issue by vanpyrzericj** [getsentry/sentry-capacitor#174]
Sentry's documentation for setting up capacitor projects is a bit outdated for Capacitor 3. 

As seen [here](https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading), Capacitor officially recommends using automatic plugin loading on android. I bumped into a couple issues when using the provided `add(SentryCapacitor.class)` approach where then a few other plugins no longer worked. Switching to the `registerPlugin` approach fixed this for me.

This callout may be worth adding to your docs, as Cap2 vs Cap3 setup.

**Comment by piotr-cz** [comment]
```java
// MainActivity.java
package com.myapp.myapp;

import com.getcapacitor.BridgeActivity;

import android.os.Bundle;
import com.getcapacitor.BridgeActivity;
import io.sentry.capacitor.SentryCapacitor;

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Initializes the Bridge
        registerPlugin(SentryCapacitor.class);
    }
}
```

**Comment by lucas-zimerman** [comment]
Thanks for pointing that out, the docs will be updated 🙂

**Comment by piotr-cz** [comment]
It's definitely worth checking, I don't register other capacitor v3 plugins either.

The Capacitor > [Custom Native Android Code](https://capacitorjs.com/docs/android/custom-code#mainactivityjava) docs mention that using `registerPlugin` method is required for *custom* plugins.
Might be that Capacitor plugins installed via npm are auto-registered by Capacitor.

**Comment by lucas-zimerman** [comment]
Closed as documented at Sentry Docs.

**Comment by deedarb** [comment]
What about capacitor 4 and capacitor 5? Is this still required to add manually? 
Documentation: "This step is not needed if you are using **Capacitor 3**"
