### ISSUE TITLE
Update @sentry dependencies to v7

### ISSUE THREAD

**Issue by piotr-cz** [getsentry/sentry-capacitor#182]
See [v7 release info](https://github.com/getsentry/sentry-javascript/releases/tag/7.0.0)

**Comment by michaeltintiuc** [comment]
Even though that PR is merged it's still behind the current v7.6.0 version. I'm asking due to Angular v14 support

**Comment by stevecarlton** [comment]
> Even though that PR is merged it's still behind the current v7.6.0 version. I'm asking due to Angular v14 support

Agreed, got all excited about seeing this published but I need Angular v14 support!

**Comment by bruno-garcia** [comment]
We released 0.7.0: https://github.com/getsentry/sentry-capacitor/releases/tag/0.7.0 with JS 7.1.1

You need 7.6.0? Could you please open a PR? We can get this merged and shipped quickly

**Comment by lucas-zimerman** [comment]
Close as completed
