### ISSUE TITLE
Angular - Uncaught SentryError: Native Client is not available, can't start on native.

### ISSUE THREAD

**Issue by dodomui** [getsentry/sentry-capacitor#193]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which package are you using?

@sentry/angular

### SDK Version

7.6.0

### Framework Version

0.6.1

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
```
@sentry/angular: ^7.6.0
@sentry/capacitor: ^0.6.1

Ionic:

   Ionic CLI                     : 6.20.1
   Ionic Framework               : @ionic/angular 6.1.13
   @angular-devkit/build-angular : 14.0.5
   @angular-devkit/schematics    : 14.0.5
   @angular/cli                  : 14.0.5
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : 3.6.0
   @capacitor/core    : 3.6.0
   @capacitor/ios     : 3.6.0
```

### Steps to Reproduce

```
error.js:8 Uncaught SentryError: Native Client is not available, can't start on native.
    at new SentryError (error.js:8:28)
    at 41406 (wrapper.js:336:25)
    at __webpack_require__ (bootstrap:19:1)
    at 88931 (index.js:2:1)
    at __webpack_require__ (bootstrap:19:1)
    at 71571 (eventorigin.js:2:1)
    at __webpack_require__ (bootstrap:19:1)
    at 82103 (scope.js:7:1)
    at __webpack_require__ (bootstrap:19:1)
    at 85208 (xhr.js:49:2)
```

### Expected Result

Had been using sentry capacitor plugin for several months.
This issue happens recently and unable to initial sentry service and App at all.

### Actual Result

```
error.js:8 Uncaught SentryError: Native Client is not available, can't start on native.
    at new SentryError (error.js:8:28)
    at 41406 (wrapper.js:336:25)
    at __webpack_require__ (bootstrap:19:1)
    at 88931 (index.js:2:1)
    at __webpack_require__ (bootstrap:19:1)
    at 71571 (eventorigin.js:2:1)
    at __webpack_require__ (bootstrap:19:1)
    at 82103 (scope.js:7:1)
    at __webpack_require__ (bootstrap:19:1)
    at 85208 (xhr.js:49:2)
```

**Comment by dodomui** [comment]
Here is my sentry version
@sentry/angular 7.6.0
@sentry/capacitor ^0.7.0

The problem still persist.

**Comment by AbhiPrasad** [comment]
@lucas-zimerman any ideas?

**Comment by EinfachHans** [comment]
I got this error on `@sentry/angular": "7.2.0"` but not on `@sentry/angular": "7.1.1"`. Not 100% sure but i think this PR is the reason: https://github.com/getsentry/sentry-javascript/pull/5260 because this new method is shown in the stacktrace

**Comment by EinfachHans** [comment]
@lucas-zimerman Web 😊 Any ETA for that next release? we want to upgrade to angular 14

**Comment by sync667** [comment]
Downgraded to Angular 13 and still have same issue.

**Comment by muuvmuuv** [comment]
Still an issue with

```
"@sentry/angular": "7.6.0",
    "@sentry/capacitor": "0.7.1",
    "@sentry/tracing": "7.6.0",
```

**Comment by EinfachHans** [comment]
@lucas-zimerman Version `0.7.1` in combination with `7.6.0` still throws this error when running in the web

**Comment by lucas-zimerman** [comment]
Ok, I may have found the source of the issue, I'll check what's enabling the Native flag on the Web code tomorrow and hopefully it's just a quick fix to unblock you from using Angular 14.

**Comment by WetCouch** [comment]
@lucas-zimerman Tried it with newer versions, didn't resolve the issue, but also don't think it's related to Angular version in my case, as I'm still on Angular 13. Until I got it wrong, and the Capacitor plugin doesn't work out of the box with the web, and I should conditionally initialize the Capacitor Sentry on mobile platforms, and Angular Sentry on web.

**Comment by sdsanders** [comment]
I'm also running into this on the web with Angular 13, @sentry/angular 7.6.0, and @sentry/capacitor 0.7.1.

**Comment by dodomui** [comment]
Update: The latest version still having the same issue.
"@sentry/angular": "^7.7.0",
"@sentry/capacitor": "^0.7.1",

**Comment by EinfachHans** [comment]
@lucas-zimerman any updates? 😬

**Comment by lucas-zimerman** [comment]
> @lucas-zimerman any updates? 😬

Hi, you were correct :D, https://github.com/getsentry/sentry-javascript/pull/5260 introduced a new call to SetContext and that sets the context before the Capacitor SDK gets initialized, 

I'll release a PR to fix this new Behavior.

**Comment by bentzibentz** [comment]
With the latest version i still have the same issue.
"@sentry/angular": "^7.12.0",
"@sentry/capacitor": "^0.9.0",

This error happens while running ionic serve.

**Comment by tharrington** [comment]
This is still an issue for me as well:

"@sentry/angular": "^7.37.1",
    "@sentry/capacitor": "^0.11.2",

**Comment by AbhiPrasad** [comment]
@tharrington if you run `npm run why @sentry/angular`, what version do you get? If it isn't `7.37.1` exactly you'll be getting problems, since that is what Capacitor `0.11.2` expects: 

https://github.com/getsentry/sentry-capacitor/blob/47e2dd124836668cc49b270b386ecf595d6c42c3/package.json#L41-L43

**Comment by tharrington** [comment]
Any update there?

**Comment by bruno-garcia** [comment]
Oh I see @tharrington opened a new one

**Comment by YehorKardashRadency** [comment]
For the ones who find this issue. The error can happen if you forget to run `npx cap sync` and sync the plugins
