### ISSUE TITLE
Ionic 6 Capacitor 3 - import { BrowserTracing } from '@sentry/tracing' fails

### ISSUE THREAD

**Issue by NilsFrkal** [getsentry/sentry-capacitor#197]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

import { BrowserTracing } from '@sentry/tracing'; on Ionic Capacitor fails with error

[ng] Error: node_modules/@sentry/tracing/node_modules/@sentry/types/types/globals.d.ts:2:11 - error TS2451: Cannot redeclare block-scoped variable '__DEBUG_BUILD__'.
[ng]
[ng] 2     const __DEBUG_BUILD__: boolean;

Ionic:

   Ionic CLI                     : 6.19.1 (d:\Development\Nodist\bin\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.14
   @angular-devkit/build-angular : 13.3.8
   @angular-devkit/schematics    : 13.3.8
   @angular/cli                  : 13.3.8
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.6.0
   @capacitor/android : 3.4.0
   @capacitor/core    : 3.6.0
   @capacitor/ios     : 3.4.3

Utility:

   cordova-res : 0.15.4
   native-run  : 1.6.0

System:

   NodeJS : v16.13.2 (D:\Development\Nodist\v-x64\16.13.2\node.exe)
   npm    : 8.1.2
   OS     : Windows 10

### Expected Result

compiles successfully

### Actual Result

Compilation fails with error 

[ng] Error: node_modules/@sentry/tracing/node_modules/@sentry/types/types/globals.d.ts:2:11 - error TS2451: Cannot redeclare block-scoped variable '__DEBUG_BUILD__'.
[ng]
[ng] 2     const __DEBUG_BUILD__: boolean;

When import is removed it compiles successfully.

**Comment by bruno-garcia** [comment]
We made a release of the Capacitor SDK today, could you please update the version and try again? https://github.com/getsentry/sentry-capacitor/releases/tag/0.7.1

It's all lined up on latest JS SDK dependencies so hopefully goes away

**Comment by NilsFrkal** [comment]
I can confirm above error is fixed. However I now have a new error "Uncaught SentryError: Native Client is not available, can't start on native." when running ionic serve. Should I open a new issue?

Also for other users: @sentry/tracing is part of @sentry/capacitor (0.7.1) and gets installed in version 0.7.6.  Do NOT npm install @sentry/tracing separately as this gets installed in version 0.7.7 and the above error returned for me.

**Comment by lucas-zimerman** [comment]
Hey, we made another release in order to fix the error `Native Client is not available on Angular`

**Comment by NilsFrkal** [comment]
Great this fixes it. @sentry/capacitor@0.8.0 with @sentry/tracing@7.6.0.

Final question please. What is the reason that tracing is part of capacitor package? As I noticed above that when installing the package separately the error had returned. This is also not very clear in the documentation. Thank you.

**Comment by vanpyrzericj** [comment]
Hey, Sentry Team! I am still having this problem. Should I open up a new issue, or can we continue on this one?

```
"@capacitor/core": "^3.5.1",
"@sentry/capacitor": "^0.10.0",
"@sentry/tracing": "^7.13.0",
"@sentry/vue": "^7.13.0,
"vue": "^3.1.5"
```

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/4707908/190914542-2254aafe-171b-4f3a-bf96-94c483cbfdb1.png">

**Comment by NilsFrkal** [comment]
@vanpyrzericj did you try to remove your "@sentry/tracing": "^7.13.0" i.e. npm uninstall --save @sentry/tracing? 

As I mentioned above, the tracing package is part of @sentry/capacitor and when you install it separately the error returns. Also there is a version difference for the standalone package. You can check via npm list @sentry/tracing and it should  show the package in version 7.12.1 underneath @sentry/capacitor:

npm list @sentry/tracing
└─┬ @sentry/capacitor@0.10.0
  └── @sentry/tracing@7.12.1

**Comment by lucas-zimerman** [comment]
> Hey, Sentry Team! I am still having this problem. Should I open up a new issue, or can we continue on this one?
> 
> ```
> "@capacitor/core": "^3.5.1",
> "@sentry/capacitor": "^0.10.0",
> "@sentry/tracing": "^7.13.0",
> "@sentry/vue": "^7.13.0,
> "vue": "^3.1.5"
> ```
> 
> ```
> import * as Sentry from "@sentry/capacitor";
> import * as SentryVue from "@sentry/vue";
> import {Integrations} from "@sentry/tracing";
> 
> Sentry.init({
>         app,
>         dsn: "***",
>         integrations: [
>             new Integrations.BrowserTracing({
>                 routingInstrumentation: SentryVue.vueRouterInstrumentation(router),
>                 tracingOrigins: ["localhost", "***", "***", /^\//],
>             }),
>         ],
>         environment: process.env.VUE_APP_SH_ENV,
>         tracesSampleRate: 1.0,
>     }, SentryVue.init);
> ```
> 
> <img alt="image" width="1001" src="https://user-images.githubusercontent.com/4707908/190914542-2254aafe-171b-4f3a-bf96-94c483cbfdb1.png">

Hi, Could you please open a new issue?
