### ISSUE TITLE
TypeError: Class constructor Scope cannot be invoked without 'new'

### ISSUE THREAD

**Issue by AliMejbar** [getsentry/sentry-capacitor#198]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
"@sentry/capacitor": "^0.7.1",

Just in case it's relevant , which I think is not . Here is my stack: 
```json
// ...
"@capacitor/cli": "^3.6.0",
"next": "^12.2.2",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"typescript": "4.7.4"
"@types/react": "18.0.15",
"@types/react-dom": "18.0.6",
// ...
```

### Steps to Reproduce

nothing special , basic configuration like the one in the tutorial : 
```ts 
import * as Sentry from '@sentry/capacitor'

const sentryConfig = {
  dsn: process.env['NEXT_PUBLIC_SENTRY_DSN'],
  release: process.env['NEXT_PUBLIC_SENTRY_PROJECT_NAME'] + '@' + version,
  dist: process.env['NEXT_PUBLIC_SENTRY_DIST'],
}

Sentry.init( sentryConfig )
```

### Expected Result

Worked normally until "0.7.1" of yesterday, code wasn't changed and was working perfectly.

### Actual Result

```console
TypeError: Class constructor Scope cannot be invoked without 'new'
    at new CapacitorScope (/Users/mohamedalimejbar/Desktop/Tabibe/App/node_modules/@sentry/capacitor/dist/build/scope.js:12:42)
    at Object.init (/Users/mohamedalimejbar/Desktop/Tabibe/App/node_modules/@sentry/capacitor/dist/build/sdk.js:30:49)
    at eval (webpack-internal:///./pages/_app.tsx:68:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  page: '/'
}
error - TypeError: Class constructor Scope cannot be invoked without 'new'
    at new CapacitorScope (/Users/mohamedalimejbar/Desktop/Tabibe/App/node_modules/@sentry/capacitor/dist/build/scope.js:12:42)
    at Object.init (/Users/mohamedalimejbar/Desktop/Tabibe/App/node_modules/@sentry/capacitor/dist/build/sdk.js:30:49)
    at eval (webpack-internal:///./pages/_app.tsx:68:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  page: '/'
}
```
![Capture d'écran 20 07 2022 à 12 17 54 p m](https://user-images.githubusercontent.com/55496459/179972533-6482a101-c1fc-49ed-9b15-99cb359ad44e.png)

**Comment by lucas-zimerman** [comment]
Was it working on version 0.7.1.? if so, are you using @sentry/react ?
Version 0.7.1 only contained a version bump of the main Javascript SDK from 7.1.01to 7.6.0, so perhaps you are using an old dependency with @sentry/capacitor?

**Comment by AliMejbar** [comment]
`Was it working on version 0.7.1.? if so, are you using @sentry/react ?`
- No it was working on 0.6.x , not in 0.7.1.

`Version 0.7.1 only contained a version bump of the main Javascript SDK from 7.1.01to 7.6.0, so perhaps you are using an old dependency with @sentry/capacitor?`
- No , all my dependencies are at latest.

**Comment by denny64** [comment]
@AliMejbar - Did you solve this issue? I'm getting the same error on v0.11.3

**Comment by AliMejbar** [comment]
> @AliMejbar - Did you solve this issue? I'm getting the same error on v0.11.3

No I ditched sentry in that app.

**Comment by nicholas-hooley** [comment]
Also experiencing this issue when using v0.11.3

Do not experience this issue with v0.6.1

**Comment by lucas-zimerman** [comment]
@nicholas-hooley sorry for the late response but what is your target on the `compilerOptions` from your typescript config?
