### ISSUE TITLE
Cannot redeclare block-scoped variable '__DEBUG_BUILD__'

### ISSUE THREAD

**Issue by michaelwijnands** [getsentry/sentry-capacitor#209]
### **Environment**
How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?

```
@sentry/angular: ^7.11.0
@sentry/capacitor: ^0.9.0

Ionic:

   Ionic Framework               : @ionic/angular 5.9.1
   @angular-devkit/build-angular : 0.1102.6
   @angular-devkit/schematics    : 11.2.7
   @angular/cli                  : 11.2.6
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI      : 3.3.2
   @capacitor/android : 3.3.2
   @capacitor/core    : 3.3.2
   @capacitor/ios     : 3.3.2
```

### **Steps to Reproduce**
We've never used @sentry/capacitor and always used @sentry/angular for web only. I tried to implement @sentry/capacitor after having upgraded to Capacitor 3. However, when trying to build the mobile apps (Android/iOS) I get the following errors:

```
Error: node_modules/@sentry/capacitor/node_modules/@sentry/types/types/globals.d.ts:2:11 - error TS2451: Cannot redeclare block-scoped variable '__DEBUG_BUILD__'.
const __DEBUG_BUILD__: boolean;
node_modules/@sentry/types/types/globals.d.ts:2:11
const __DEBUG_BUILD__: boolean;
'__DEBUG_BUILD__' was also declared here.

Error: node_modules/@sentry/types/types/globals.d.ts:2:11 - error TS2451: Cannot redeclare block-scoped variable '__DEBUG_BUILD__'.
const __DEBUG_BUILD__: boolean;
node_modules/@sentry/capacitor/node_modules/@sentry/types/types/globals.d.ts:2:11
const __DEBUG_BUILD__: boolean;
'__DEBUG_BUILD__' was also declared here.
```

**Comment by lucas-zimerman** [comment]
Maybe you are running into the same situation as this one? 
https://github.com/getsentry/sentry-javascript/issues/5427

**Comment by mmjr-x** [comment]
I am also facing this problem, seems to be because the latest version ( 0.9.0 ) of @sentry/capacitor depends on @sentry/types 7.8.1 and the latest version of @sentry/angular (7.12.0) depends on @sentry/types 7.12.0 . This causes npm to not consolidate the dependencies and thus resulting in the error.

**Comment by lucas-zimerman** [comment]
> I am also facing this problem, seems to be because the latest version ( 0.9.0 ) of @sentry/capacitor depends on @sentry/types 7.8.1 and the latest version of @sentry/angular (7.12.0) depends on @sentry/types 7.12.0 . This causes npm to not consolidate the dependencies and thus resulting in the error.

mmm if so I'll bump the dependencies version this week.

**Comment by mmjr-x** [comment]
Although the @sentry/types is the only one that causes a hard error, the following (peer)deps should probably be bumped to 7.12.0 as well:

- "@sentry/angular": "7.8.1",
-     "@sentry/react": "7.8.1",
-     "@sentry/vue": "7.8.1"

- "@sentry/browser": "7.8.1",
-     "@sentry/core": "7.8.1",
-     "@sentry/hub": "7.8.1",
-     "@sentry/integrations": "7.8.1",
-     "@sentry/tracing": "7.8.1",
-     "@sentry/types": "7.8.1",
-     "@sentry/utils": "7.8.1",

- "@sentry-internal/eslint-config-sdk": "7.8.1",
-     "@sentry-internal/eslint-plugin-sdk": "7.8.1",

Besides that "@sentry/wizard" and "@sentry/typescript" might need to be bumped as well (although I am not 100% sure about this)

**Comment by mmjr-x** [comment]
@bruno-garcia Thanks for the fix! Any idea when this will be released? :)

**Comment by mileszim** [comment]
Still getting this

**Comment by lucas-zimerman** [comment]
> Still getting this

Hi mileszim, how are you installing sentry capacitor/angular, with npm or yarn?

**Comment by mileszim** [comment]
@lucas-zimerman we're using sentry capacitor + ember, and I managed to get it to work by locking all versions to `7.12.1`. the package.json entry looks like:

```
    "@sentry/browser": "7.12.1",
    "@sentry/capacitor": "0.10.0",
    "@sentry/cli": "^2.5.2",
    "@sentry/ember": "7.12.1",
    "@sentry/integrations": "7.12.1",
    "@sentry/rrweb": "^0.3.3",
```
