### ISSUE TITLE
Add integration test to validate for Sentry dependencies 

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-capacitor#210]
- Check if there were no build errors when using an dependency SDK (such as Sentry Angular) above the  version used by Sentry Capacitor.

one example is Sentry Capacitor 10 requires Sentry Angular 10, but after a week, version 11 from angular is released and it breaks the build if used with Sentry Capacitor 10.

**Comment by kahest** [comment]
Probably good approach to set up a test matrix

**Comment by lucas-zimerman** [comment]
This task currently has no value since the SDK only supports a fixed version of Sentry JavaScript.
