### ISSUE TITLE
cap sync ios failing for version 0.10.0

### ISSUE THREAD

**Issue by ekrapfl** [getsentry/sentry-capacitor#217]
### Environment

I am running the latest Capacitor version (4.2.0), as well as the latest `@sentry/capacitor` version (0.10.0)

### Steps to Reproduce

1. Pull this minimal reproduction repo: https://github.com/ekrapfl/sentry-test
1. `npm ci`
1. `npm run build`
1. `npx cap sync`

### Expected Result

No errors when installing and syncing the latest version of `@sentry/capacitor`

### Actual Result

You will see the following error in the console from the `cap sync`
```
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] Analyzing dependencies
        [!] CocoaPods could not find compatible versions for pod "Sentry":
        In Podfile:
        SentryCapacitor (from `../../node_modules/@sentry/capacitor`) was resolved to 0.10.0, which depends on
        Sentry (~> 7.23.0)
        
        None of your spec sources contain a spec satisfying the dependency: `Sentry (~> 7.23.0)`.
        
        You have either:
        * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
        * mistyped the name or version.
        * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by lucas-zimerman** [comment]
thanks for opening the issue with a sample :D 

Have you tried to run `pod install --repo-update`?  I was able to reproduce it but I no longer can repro it after running the pod update.

**Comment by lucas-zimerman** [comment]
No worries, I also faced the same problem on a Mac M1 (it always breaks something when the OS updates haha)
Glad it worked on your end, for the time being I will just update the troubleshooting page for cases like this :)
