### ISSUE TITLE
SentrySystemEventBreadcrumbs.m file crashing on app startup

### ISSUE THREAD

**Issue by mattwyld-north27** [getsentry/sentry-capacitor#219]
### Environment

    "@angular/common": "^14.0.0",
    "@angular/core": "^14.0.0",
    "@capacitor/ios": "3.5.1",
    "@sentry/angular": "^7.12.1",
    "@sentry/capacitor": "^0.10.0",
    
    Xcode version 14

### Steps to Reproduce

Followed the setup for capacitor outlined here: https://docs.sentry.io/platforms/javascript/guides/capacitor/ionic/

### Expected Result

I can run the iPhone app

### Actual Result

iPhone app crashes on startup with the following:

![Screenshot 2022-09-22 at 09 17 05](https://user-images.githubusercontent.com/107503177/191724955-186d474c-b095-4698-ac2d-42d4db2e42b9.png)

I've tried disabling breadcrumbs using `maxBreadcrumbs: 0,` in the `Sentry.init` and using
```integrations(integrations) {
       // integrations will be all default integrations
       return integrations.filter((integration) => integration.name !== 'Breadcrumbs');
     },```

**Comment by lucas-zimerman** [comment]
Hi @mattwyld-north27 and thanks for your report!
was the error captured on a real device or on a Simulator? Which iOS version were you running?

I have a feeling the issue is not exactly the breadcrumbs but more likely the integration not running at the main thread

**Comment by lucas-zimerman** [comment]
> Hi @lucas-zimerman, thanks for getting back to me! The error was captured on a real device:
> 
> iPhone 12 Pro iOS Version: 15.6.1
> 
> I hope this helps, let me know if you need anything else

Sure that helps :), by any chance is it possible to check if the error persists if you disable firebase from your code?

**Comment by mattwyld-north27** [comment]
The app has firebase pretty deeply embedded in it, so might be a task to disable it. I'll see what I can do, and get back to you. In the mean time I also had an issue on the android side, not sure if its related. I can post it here but let me know if it's unrelated and I'll open a new ticket for it

![image](https://user-images.githubusercontent.com/107503177/192365491-6da2ac5e-408c-4195-93db-e58e21050890.png)
