### ISSUE TITLE
Yarn PnP: Failed to load 'SentryCapacitor' podspec for version 0.10.0

### ISSUE THREAD

**Issue by chitchu** [getsentry/sentry-capacitor#221]
### Environment

macOS 12.6 / zsh / Yarn v2 or greater

### Steps to Reproduce

1. Must use Yarn PnP (v2 or greater)
2. Run `cap sync ios`

### Expected Result

```
✔ Updating iOS native dependencies with pod install in 18.06s
✔ update ios in 18.28s
```

### Actual Result

```
[error] Analyzing dependencies
        [!] Failed to load 'SentryCapacitor' podspec:
        [!] Invalid `SentryCapacitor.podspec` file: No such file or directory @ rb_sysopen -
```

### Other notes

I've investigated a little, and the cause is [SentryCapacitor.podspec](https://github.com/getsentry/sentry-capacitor/blob/main/SentryCapacitor.podspec#L14) relatively attempts to read `@capacitor/core/package.json` which doesn't exist in a Yarn PnP enabled environment.

**Comment by lucas-zimerman** [comment]
Thanks for the feedback!
By any chance do you know where @Capacitor package.json could be found?
As a fallback, I think it's ok to setup the minimum version as 13.0 for iOS in order to be compatible with Capacitor 4

**Comment by chitchu** [comment]
Yarn places all `node_modules` within a `.yarn/cache` directory (configurable) in .zip format. They have an "unplugged" configuration where the dependency is stored in a directory. The recommended method is to always use `require.resolve` which I'm not sure exists in a `.podspec` file.

**Comment by lucas-zimerman** [comment]
Hi @chitchu thanks for your return.
Could you post a minimal repro of this? I ask because I was going to give a try on Yarn PnP on an empty Ionic project, but it is spitting tons of errors in regard to unqualified paths to a lot of inner dependencies of dependencies.

**Comment by chitchu** [comment]
Sure thing. Here's a very minimal repro: https://github.com/chitchu/yarn-sentry-capacitor

Instructions included as a readme.

**Comment by lucas-zimerman** [comment]
@chitchu A new version containing a fix for the pnp  buid was released. If there are any other issues please let me know or feel free to open another issue :)
