### ISSUE TITLE
Source code was not found (Android + capacitor)

### ISSUE THREAD

**Issue by hoisel** [getsentry/sentry-capacitor#226]
### System 
```
   NodeJS : v14.17.4
   npm    : 7.22.0
   OS     : Linux 5.4
```

### Environment
angular + capacitor running on android 10  device.

```json
    "@sentry/angular": "^7.8.1",
    "@sentry/capacitor": "^0.9.0",
    "@capacitor/android": "^3.5.1",
    "@angular/core": "14.0.1",
```

### Steps to Reproduce

1.Configure:

```ts
import * as SentryAngular from '@sentry/angular';
import { ErrorHandlerOptions, SentryErrorHandler } from '@sentry/angular';
import * as Sentry from '@sentry/capacitor';

Sentry.init(
  {
    dsn: process.env.SENTRY_DSN,
    release: process.env.SENTRY_RELEASE,
    environment: process.env.ENV
  },
  // Forward the init method from @sentry/angular
  SentryAngular.init
);
```

2. Run angular build and deploy to Android 10 device using Android Studio:

4. Create release and upload source-map using sentry-cli: 

![Screenshot from 2022-09-29 19-46-06](https://user-images.githubusercontent.com/400244/193155450-589c8941-3067-4dae-b8d4-021d25643ec1.png)

### Expected Result
Artifact names matching stack trace frames.

### Actual Result
Source Code was not found:

![Screenshot from 2022-09-29 19-50-49](https://user-images.githubusercontent.com/400244/193155935-62abe53f-b79c-4740-94b9-2ffc3367d75e.png)

Running `sentry-cli sourcemaps explain EVENT_ID`:

![image](https://user-images.githubusercontent.com/400244/193156171-9a96fe25-2146-4902-b901-d6075f1c04f4.png)

*Note: everything works perfectly on web brower.*

**Comment by lucas-zimerman** [comment]
Thanks for opening the issue :D 

Would you mind sharing the sentry-cli command used for sending the sourcemaps? also, have you informed the dist 535 when uploading the sourcemaps?

**Comment by hoisel** [comment]
Hi @lucas-zimerman,

These are the commands that were executed in the ci, where our app release was generated:

```
npx sentry-cli releases new -p mobile-app -o ORG_SLUG --auth-token AUTH_TOKEN mobile-app@4.63.0
npx sentry-cli releases set-commits -p mobile-app -o ORG_SLUG --auth-token AUTH_TOKEN --auto mobile-app@4.63.0
npx sentry-cli releases -o ORG_SLUG -p mobile-app --auth-token AUTH_TOKEN files mobile-app@4.63.0 upload-sourcemaps ./apps/mobile-app/www
```

I haven`t informed the dist 535 when uploading the sourcemaps, as far as I know.

**Comment by hoisel** [comment]
Hi @lucas-zimerman,
The issue was resolved by informing the dist number correctly. Thanks!

**Comment by alvarollmenezes** [comment]
@lucas-zimerman  Thank you for the tip, it was assertive.

Just as a PS, I'd like to address that it's hard to get (especially on hybrid apps) this behavior, where the dist number is filled transparently on some platform(s). Seems unexpected.

**Comment by lucas-zimerman** [comment]
Glad it was helpful :D 

Maybe there was a behavior change on the Native SDKs in regard to the dist parameter, but if your events contain the tag `dist` then you must inform the dist when sending the source-maps otherwise Sentry will not find the Source-maps for that release+dist.
