### ISSUE TITLE
Events not being sent as logs indicate sent

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry-capacitor#228]
### Environment

0.10.1 (latest)

### Steps to Reproduce

Details in https://getsentry.atlassian.net/browse/ISSUE-1571

### Expected Result

Events to be sent to Sentry

### Actual Result

Logs return 200 but no events were found in Sentry.

**Comment by lucas-zimerman** [comment]
Hi @JLuse I don't have access to ISSUE-1571 
To better understand the problem, I'll ask some questions:

- Do transactions work?
- By the events not found, how did you perform the search for the given event? (Looking for the latest event on discover, on the issues page, by the event id, ...)
- Which platform have you tested? (Android, iOS, WEB)
- Were you using Capacitor 3 or 4?
- Were you using any additional framework? (Vue, Angular or React)

**Comment by JLuse** [comment]
Thanks, @lucas-zimerman. Waiting to hear back from the customer but will try and gather this information.
