### ISSUE TITLE
Ivestigate dist being set on android but not on iOS 

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-capacitor#229]
It seems like when the user doesn't inform the dist, on Android it'll automatically set the app revision code as the dist tag where on iOS it'll not be set, this leads to an app with two dist values.
Check if this is an expected behavior, otherwise we need to fix it.

**Comment by inpt333** [comment]
Hi @lucas-zimerman , this issue causes that the errors reported from iOS by the plugin are not properly linked to their corresponding source map in Sentry. To solve it, we need to set the field _dist_ directly in Angular and align its value to the one used in our Webpack configuration (we use Webpack to do the source map upload). Unfortunately, to align both values, we need to inject our environment variables in Angular via Webpack which we would like to avoid.

Could it be possible that your plugin uses as value for _dist_ the key _CFBundleVersion_ from the Info.plist, similar to what you do with Android and the version code?
