### ISSUE TITLE
Publish `@sentry/capacitor` to npm

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-capacitor#23]
make a first release to npm to get the Android support out there.

See #21 

Revert this change once it's live; https://github.com/getsentry/sentry-docs/pull/3041/files

**Comment by bruno-garcia** [comment]
Relates to #24

**Comment by erikwalle** [comment]
I'd be super happy if you'd just say in the readme how to get it working with basic ionic.. I cloned it to my /src directory, npm i src/sentry-capacitor went well but my runtime can't find it.

**Comment by Ahmedesayed** [comment]
any updates ?

**Comment by bruno-garcia** [comment]
@Ahmedesayed preview coming out in a few days
