### ISSUE TITLE
Duplicate Breadcrumbs on Android

### ISSUE THREAD

**Issue by fr3fou** [getsentry/sentry-capacitor#232]
### Environment

```json
    "@sentry/capacitor": "0.9.0",
    "@sentry/react": "7.8.1",
    "@sentry/tracing": "7.8.1",
```
Sentry SaaS

Haven't upgraded to 0.10.x, as we're still running Capacitor 3.

### Steps to Reproduce

1. Use a Capacitor app on an Android device and cause an exception 
2. Open the Sentry dashboard
![image](https://user-images.githubusercontent.com/1344906/194822927-2315c8af-258f-4d07-8109-8f73b0d4dd4a.png)

### Expected Result

Breadcrumbs shouldn't be duplicated.

### Actual Result

The breadcrumbs are duplicated.

My integration in the JS side is nothing special:

```ts
Sentry.init(
  {
    dsn: SENTRY_DSN,
    integrations: [new BrowserTracing()],
    release: `app-v1@${VERSION?.trim() ?? gitInfo.commit.shortHash}`,
    dist: gitInfo.commit.shortHash,
    debug: false,
    beforeBreadcrumb(breadcrumb, hint) {
      if (breadcrumb.category === "xhr") {
        const response = hint?.xhr.response ?? {}
        const request = hint?.input ?? {}
        breadcrumb.data = {
          ...breadcrumb.data,
          request,
          response,
        }
      }
      return breadcrumb
    },
  },
  SentryReact.init
)
```

**Comment by lucas-zimerman** [comment]
Hi, thanks for opning this issue :D
We'll investigate what's going on. In the meantime, does the duplication also happens without the beforeBreadcrumb?
