### ISSUE TITLE
Snyk security test

### ISSUE THREAD

**Issue by mwyld** [getsentry/sentry-capacitor#234]
### Environment

Capacitor version 4

### Steps to Reproduce

- Installed Snyk
- Ran it against a project with this plugin

### Expected Result

- No security errors appear

### Actual Result

![Screenshot 2022-10-12 at 22 26 36](https://user-images.githubusercontent.com/12820928/195451222-8e3b0c67-408a-435a-9b28-99c7d7cde27b.png)
![Screenshot 2022-10-12 at 22 27 09](https://user-images.githubusercontent.com/12820928/195451224-0a3de250-0013-4c8a-aad3-0c2a9988bb6a.png)

**Comment by krystofwoldrich** [comment]
Thanks for the information.

Sounds like we should upgrade cli in wizard (and then wizard in capacitor), as the latest version of cli has npmlog@6.X.X which I assume doesn't suffer from the ReDos.

**Comment by kahest** [comment]
The offending dependencies (`@sentry/wizard@1.3.0`) have been removed starting at release [0.11.5](https://github.com/getsentry/sentry-capacitor/releases/tag/0.11.5)
