### ISSUE TITLE
Purpose of the Sentry Capacitor SDK vs. the Sentry iOS & Android ones

### ISSUE THREAD

**Issue by laurentgoudet** [getsentry/sentry-capacitor#26]
We are currently running an iOS & Android Capacitor app, and have integrated the Sentry iOS & Android SDKs, in addition to the Sentry JS SDK we were already using for the web app itself.

I know this is an alpha project but I was wondering what was the plan for it, i.e. what would it bring more that isn't provided by the Sentry native SDKs already. Maybe adding a section in the README would help people decide if they need it or not.

**Comment by bruno-garcia** [comment]
This SDK will be able to synchronize scope data between the JS layer and the native SDKs, so if you set the user in JS, and a crash happens on the native layer, you get those captured.

Also, if there's an error in JS, it will affect your release health stats. By using just the native+JS, the JS layer sends events directly to Sentry and the native layer isnt' aware of those errors.

Also, it'll provide offline caching of the JS events. That and a few more things. 

We plan to focus on this SDK in this quarter.
