### ISSUE TITLE
Status of the plugin development?

### ISSUE THREAD

**Issue by michalsisak** [getsentry/sentry-capacitor#27]
First of all, thank you for the work you are doing in order to get a Capacitor's version of Sentry. While Cordova's version works for majority of Sentry features, there are few things the plugin just can't do.

I would like to ask you what is the current status on the repo. There hasn't been any development since February. The plugin is stuck in Android Alpha. 

Can you please explain if there is some problem or what is stopping you from further development?

Thank you one more time, I understand that sometimes you must prioritise other work but I am certain there are many developers eagerly waiting for this plugin to became reality.

**Comment by yoyo930021** [comment]
Looking forward to this plugin.
If it needs some help, I can send some PRs.

**Comment by bruno-garcia** [comment]
> First of all, thank you for the work you are doing in order to get a Capacitor's version of Sentry. While Cordova's version works for majority of Sentry features, there are few things the plugin just can't do.

What features from Cordova are you missing? We've [recently release version 1.0.0 with a lot of new features](https://github.com/getsentry/sentry-cordova/releases/tag/v1.0.0) such as release health, native crash support, performance monitoring, etc.

> I would like to ask you what is the current status on the repo. There hasn't been any development since February. The plugin is stuck in Android Alpha.

We're going to focus on it in Q2, so expect big changes and releases coming in the near future.

> Can you please explain if there is some problem or what is stopping you from further development?

Mainly resourcing. Sentry has a **lot** of SDKs and things change quickly. The Cordova SDK didn't get fixes and updates for a long time so we wanted to take care of it before we could really focus on adding something new. 

> Thank you one more time, I understand that sometimes you must prioritise other work but I am certain there are many developers eagerly waiting for this plugin to became reality.

Thank you! We appreciate that and if you can, please help us test our alphas and beta releases (they'll come in the next weeks). Also give us feedback on [Discord ](https://discord.gg/sentry) if things work or not for you to help us drive development here. Your feedback really helps us.

**Comment by michalsisak** [comment]
Thank you very much for such a detailed answer!

The big problem with Cordova's plugin is the fact it can't understand source maps well. Capacitor uses different URL and Sentry can't connect an error to uploaded source maps. There are few ways how to get it work but I have been unsuccessful so far. So my hope is this new plugin will handle source maps better.

Thanks again for the work and looking forward to testing it in the future!

**Comment by bruno-garcia** [comment]
Thanks for bringing that to our attention. We'll make sure to take a look. I'll keep this open and pinned for now.

**Comment by michalsisak** [comment]
Then it that case I am sending this [video](https://youtu.be/iGuqUtHGTj8?t=1992) from Ionic Sentry webinar where a hack is shown as to how recognize sourcemaps. (Didn't work for me fo some reason though).

Could be helpful for this project.
