### ISSUE TITLE
Support for Sentry/Replay

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-capacitor#279]
Currently the SDK isn't working with Replays, it attached the Replay id on the breadcrumb but the replay itself wasn't sent, further investigation is required for the case:

![image](https://user-images.githubusercontent.com/8229322/207326268-532ae6ad-4183-4389-949b-54d68e924643.png)

**Comment by lucas-zimerman** [comment]
The envelope sent by the web X app seems different, when running just on the browser, I get the envelope payload as the following one
![image](https://user-images.githubusercontent.com/8229322/208648731-f78ca738-b4b5-4832-8fa8-5aed65ea0df8.png)
But when sending by the mobile I noticed the segment data was missing and also the replay attachment seems to be on an unexpected format 
![image](https://user-images.githubusercontent.com/8229322/208648911-4f1f24cc-a995-4bad-b8da-9942ee0938ae.png)

I am not entirely sure if the second screenshot is accepted by the replay attachment, but I'll assume it's not since it didn't show any attachment on the replay sent.

**Comment by lucas-zimerman** [comment]
I am having a bit of trouble since the project isn't building due to external repositories being unstable/missing

**Comment by lucas-zimerman** [comment]
Ok so, this is the main problem 
https://github.com/getsentry/sentry-capacitor/blob/8f74052464e9dfc70237c973cccf90ce2b81e16f/src/wrapper.ts#L73-L75
We can't serialize it as json since the data isn't a json serializable data, but at the same time, we can't convert it to a string since there'll be data loss/conversion ( `new Decoder('UTF-8')` )

**Comment by krystofwoldrich** [comment]
In React-Native we assemble the whole envelope in the JS layer and send a bytes array to the native SDKs.

https://github.com/getsentry/sentry-react-native/blob/ca810b988e532633b662192ab286e8fc93324e46/src/js/wrapper.ts#L152

**Comment by bruno-garcia** [comment]
Sounds like a good refactor for capacitor
