### ISSUE TITLE
Release GA on npm 

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-capacitor#29]
This issue will track making the Capacitor GA with support to Android and iOS.

The expected features are: Native crash support, JS-land errors, release health and performance monitoring (the API to track timing information such as transactions and spans).

Related to #23 #21 #27

**Comment by erikwalle** [comment]
@bruno-garcia activity kinda dried up again, will we see this on NPM soon? Thanks!

**Comment by bruno-garcia** [comment]
@jennmueng just started [making some sizeble changes](https://github.com/getsentry/sentry-capacitor/commits?author=jennmueng) here and is driving the project forward. It's planned to be worked through GA now

**Comment by erikwalle** [comment]
@bruno-garcia what does GA stand for?
@jennmueng sorry to bug, any rough timeline for npm availability?

Thank you so much all!

**Comment by bruno-garcia** [comment]
GA = general availability.
We plan to release it by the end of August.
