### ISSUE TITLE
Consider relaxing peerDependency version

### ISSUE THREAD

**Issue by kenny-f** [getsentry/sentry-capacitor#317]
I'm in the process of upgrading all sentry packages in our application to: 
```
    "@sentry/capacitor": "^0.11.1",
    "@sentry/node": "^7.36.0",
    "@sentry/react": "^7.36.0",
    "@sentry/tracing": "^7.36.0",
```

However I'm getting this error on `npm install`

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @sentry/capacitor@0.11.1
npm ERR! Found: @sentry/react@7.36.0
npm ERR! node_modules/@sentry/react
npm ERR!   @sentry/react@"^7.36.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @sentry/react@"7.31.1" from @sentry/capacitor@0.11.1
npm ERR! node_modules/@sentry/capacitor
npm ERR!   @sentry/capacitor@"^0.11.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @sentry/react@7.31.1
npm ERR! node_modules/@sentry/react
npm ERR!   peerOptional @sentry/react@"7.31.1" from @sentry/capacitor@0.11.1
npm ERR!   node_modules/@sentry/capacitor
npm ERR!     @sentry/capacitor@"^0.11.1" from the root project
```

This is because there is a strict [peerDependency on @sentry/react to version 7.31.1](https://github.com/getsentry/sentry-capacitor/blob/main/package.json#L42)

Is it possible to specify a range instead?

**Comment by cgrabmann** [comment]
Hi

could you please also exclude "@sentry/electron" from the sibling-check, because it does not have the same versions as the core sentry packages.

I had to disable the sibling-check in our Nx-Monorepo because the install would fail otherwise.

**Comment by lucas-zimerman** [comment]
Thanks for the update @cgrabmann, This will be fixed soon :D 
About the sibling, I am aware it's not ideal, but I'll double check the reasons why it should be used that way.

**Comment by lucas-zimerman** [comment]
Hi @kenny-f, due to the complexity of the SDKs we'll keep the peerDependency strict to avoid adding extra maintenance burden of using the SDK with different types of dependencies.

About the electron issue it should be fixed on the latest version.

**Comment by lucas-zimerman** [comment]
Hi @kenny-f, due to the complexity of the SDKs we'll keep the peerDependency strict to avoid adding extra maintenance burden of using the SDK with different types of dependencies.

About the electron issue it should be fixed on the latest version.
