### ISSUE TITLE
Replay: recording fails with CSP errors

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-capacitor#318]
The playback seems far from what the user saw.

![image](https://user-images.githubusercontent.com/1633368/218188803-0d941d81-1d05-41eb-bb89-1b33de4983e8.png)

Reproed on iOS 16.0.3

SDK: `7.31.1`

**Comment by bruno-garcia** [comment]
@mhartington shared a work around for stack traces he used in the past that might be useful here:

https://github.com/mhartington/sentry-ng-ionic/blob/cfbf173cb80b89d5e43a14cfb6991741996633dc/src/main.ts#L8-L37

**Comment by bruno-garcia** [comment]
Possibly issues are related to the options combination: https://docs.sentry.io/platforms/javascript/session-replay/privacy/#privacy-configuration

I believe we shouldn't expose capturing Media. Since we can't fetch that at the time of Replay (those are all localhost resources).

Perhaps with `blockAllMedia: true` which is default, without allowing customers to change this?

**Comment by bruno-garcia** [comment]
@mhartington suggested:

> We customize the scheme and host name in native to support browser apis that are blocked when not loaded via https

```
server?: {
    /**
     * Configure the local hostname of the device.
     *
     * It is recommended to keep this as `localhost` as it allows the use of
     * Web APIs that would otherwise require a [secure
     * context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)
     * such as
     * [`navigator.geolocation`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/geolocation)
     * and
     * [`MediaDevices.getUserMedia`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia).
     *
     * @since 1.0.0
     * @default localhost
     */
    hostname?: string;

    /**
     * Configure the local scheme on iOS.
     *
     * [Can't be set to schemes that the WKWebView already handles, such as http or https](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/2875766-seturlschemehandler)
     * This can be useful when migrating from
     * [`cordova-plugin-ionic-webview`](https://github.com/ionic-team/cordova-plugin-ionic-webview),
     * where the default scheme on iOS is `ionic`.
     *
     * @since 1.2.0
     * @default capacitor
     */
    iosScheme?: string;

    /**
     * Configure the local scheme on Android.
     *
     * @since 1.2.0
     * @default http
     */
    androidScheme?: string;
```

See: https://capacitorjs.com/docs/config#schema

**Comment by lucas-zimerman** [comment]
About blockAllMedia, what blockAllMedia actually does? I tried to play with it on a React app (without Capacitor/Ionic) and i got mixed results:

private ip + blockAllMedia false
![image](https://user-images.githubusercontent.com/8229322/218703124-aa1fe0d1-e1d5-4e60-84d8-3331924691c4.png)
https://sentry-sdks.sentry.io/replays/sentry-capacitor:7d74587d166b4717acb5a64808c8729b/?referrer=%2Fdiscover%2F%3AeventSlug%2F&t=2&t_main=console

local host + blockAllMedia false
![image](https://user-images.githubusercontent.com/8229322/218703795-0949747f-4b2d-4497-b0f3-093453adb55f.png)
https://sentry-sdks.sentry.io/replays/sentry-capacitor:78b2c09236cd410b871fdfa61aa82781/?referrer=%2Fdiscover%2F%3AeventSlug%2F&t=4&t_main=console

private ip + blockAllMedia true
![image](https://user-images.githubusercontent.com/8229322/218704852-5c8f58ae-0b2e-4fed-b21a-d255523f8a22.png)
https://sentry-sdks.sentry.io/replays/sentry-capacitor:941239485dad4160a84e89cb33727d27/?referrer=%2Fdiscover%2F%3AeventSlug%2F&t=3&t_main=console

localhost + blockAllMedia true
![image](https://user-images.githubusercontent.com/8229322/218705290-6e739450-2604-4314-ae3b-625501ca33f2.png)
https://sentry-sdks.sentry.io/replays/sentry-capacitor:1810352112f44617855739ff900686c5/?referrer=%2Fdiscover%2F%3AeventSlug%2F&t=3&t_main=network

**Comment by lucas-zimerman** [comment]
One detail that I noticed that's generating CSP errors is that Capacitor adds to the head of the document the following base:
`<base href="http://localhost/">`

The same can also be replicated if other applications adds the base href as localhost as seen on this sample replay (without using capacitor/ionic):
https://sentry-sdks.sentry.io/replays/sentry-capacitor:37499c8735df470d9545817c6c40208d/?referrer=%2Fdiscover%2F%3AeventSlug%2F&t=7&t_main=console

**Comment by lucas-zimerman** [comment]
I am closing this issue because the CSP errors are no longer happening.
