### ISSUE TITLE
App not opens after nativeCrash calling

### ISSUE THREAD

**Issue by sinanverve7** [getsentry/sentry-capacitor#328]
### Environment
iOs

What version are you running? Etc.
@sentry/capacitor 0.11.2
@sentry/angular 7.37.1

### Steps to Reproduce

i had integrated like you mentioned in doucmentation

in my app.module.ts file
import * as Sentry from "@sentry/capacitor";
import * as SentryAngular from "@sentry/angular";
..
```
Sentry.init({
  dsn: my-dsn
}, SentryAngular.init);

```

i added ErrorHandler from @angular/core
```
  providers: [
    {
      provide: ErrorHandler,
      // Attach the Sentry ErrorHandler
      useValue: SentryAngular.createErrorHandler(),
    },
   ]
   ```
   from my home.component.ts
   
   ```
  forceCrash(){
         nativeCrash();
     }
```
     
     i got a thread violation error because of that app was not opening only showing splash screen 
     
     then i replaced sentryUiDeviceWrapper.m file
     
     at the line 15 
     to this
```
     - (instancetype)init
{
    if (self = [super init]) {
        // Needed to read the device orientation on demand
        if (!UIDevice.currentDevice.isGeneratingDeviceOrientationNotifications) {
            self.cleanupDeviceOrientationNotifications = YES;
            [UIDevice.currentDevice beginGeneratingDeviceOrientationNotifications];
        }

        // Needed so we can read the battery level
        if (!UIDevice.currentDevice.isBatteryMonitoringEnabled) {
            self.cleanupBatteryMonitoring = YES;
            UIDevice.currentDevice.batteryMonitoringEnabled = YES;
        }
    }
    return self;
}
```
all other code in that file is same, i got above code from chatGpt
then it worked i was able to force crash my application

### Expected Result

app crashes.after killing the app ,on opening againg app works normally

### Actual Result

app crashes,after killing when i try to open the app only splash screen is showing i have to build again in my xcode to run the app again

in my app sentry dashboard every time this message shows
exceptionHandler.handleError is not a function. (In 'exceptionHandler.handleError(error)', 'exceptionHandler.handleError' is undefined)
but i follwed official documentation and exceptionHandler implemented correctly

**Comment by sinanverve7** [comment]
when i removed the sentryUiDeviceWrapper.m file's modification

iam getting below error actually iam wondering even if i follwed stricly documentation why iam getting this error
⚡️  To Native ->  SentryCapacitor initNativeSdk 88714969
⚡️  To Native ->  SentryCapacitor setContext 88714970
2023-02-28 17:59:35.191534+0530 QuackQuack[24496:902547] failure in assertBarrierOnQueue of <FBSSerialQueue:0x2823c1200> (FBSSerialQueue.m:121) : threading violation: expected the main thread
(lldb)

**Comment by sinanverve7** [comment]
Hi team.
i was checking native crash with connecting my iphone through datacable when i removed datacable and made app force crash , it was crashing and exiting app, and on opening again it is opening as usual.
actually now previous issue is not resolved. thread violation 


`
- (instancetype)init
{
    if (self = [super init]) {
        // Needed to read the device orientation on demand
        if (![UIDevice currentDevice].isGeneratingDeviceOrientationNotifications) {
            self.cleanupDeviceOrientationNotifications = YES;
            dispatch_async(dispatch_get_main_queue(), ^{
                [[UIDevice currentDevice] beginGeneratingDeviceOrientationNotifications];
            });
        }

        // Needed so we can read the battery level
        if (![UIDevice currentDevice].isBatteryMonitoringEnabled) {
            self.cleanupBatteryMonitoring = YES;
            dispatch_async(dispatch_get_main_queue(), ^{
                [UIDevice currentDevice].batteryMonitoringEnabled = YES;
            });
        }
    }
    return self;
}
`

only adding above code i was able to open other wise build is succeeding ,but iam getting thread violation error

**Comment by lucas-zimerman** [comment]
Hi @sinanverve7 The version 0.13.0-beta.1 contains fixes in regard to some crashes from the SDK on iOS, could you check if this version fixed your issue?
