### ISSUE TITLE
Sentry Replay: Inaccurate element positionings

### ISSUE THREAD

**Issue by anonimitoraf** [getsentry/sentry-capacitor#329]
### Environment
```
    "@capacitor/app": "4.1.1",
    "@capacitor/core": "4.7.0",
    
    "@sentry/capacitor": "^0.11.2",
    "@sentry/replay": "^7.40.0",
```

### Steps to Reproduce

1. Clone https://github.com/anonimitoraf/sentry-capacitor-replay-repro
2. Fill in the redacted `dsn` string under `src/sentry.ts`
3. Run `yarn && yarn start`
4. Go to http://localhost:3000
5. Go to Tab 2 > Click on the `Boom boom boom` button
7. View the Sentry Replay
8. Notice that all the elements' positions are way off in the replay

### Expected Result

The Replay should look exactly like the app

### Actual Result

https://user-images.githubusercontent.com/15933322/222959138-0cad29b9-e1e5-4683-9ec2-9be86d2b7004.mov

**Comment by lucas-zimerman** [comment]
Hi, just wondering, are you using Safari for the app?

**Comment by anonimitoraf** [comment]
Hi, yes. Although I believe it happens for Chrome too. I'll try to verify later

**Comment by anonimitoraf** [comment]
Sorry I forgot to report back. This happens in Chrome as well.

**Comment by anonimitoraf** [comment]
Hi @kahest , thanks for re-opening. Any ideas on how this can be fixed? I'm very keen to use Sentry Replays and also happy to help in the implementation, if I can

**Comment by kahest** [comment]
Hi @anonimitoraf - thanks for the report and the repro! 🙏 
@bruno-garcia do you think this is Capacitor/Mobile related?

**Comment by gugahoi** [comment]
Just thought that I'd point out that the recording above is in a browser and not in mobile. I've tried sessions replay tools in Capacitor before and usually there is a problem with recording in the native app but never in a browser. Just thought I'd share my experience to try and contribute to the conversation as I would love to find a way to get this working in Capacitor based native apps.

**Comment by bruno-garcia** [comment]
Thanks for the repro. If this happens on the browser too (outside of a mobile app I mean) it's surprising.

**Comment by anonimitoraf** [comment]
It seems to happen on a browser too (see ticket description). I tried it out on both Safari and Chrome (Mac M1 if it matters)

**Comment by bruno-garcia** [comment]
We'll do a preview of capacitor on the new Sentry Replay package (based on rrweb2.0): `v7.70.0-beta.1`

**Comment by bruno-garcia** [comment]
Release is live! Hopefully addresses the issue

**Comment by anonimitoraf** [comment]
Thanks @bruno-garcia ! Will report back

**Comment by Cullima** [comment]
> Thanks @bruno-garcia ! Will report back

Did you get anywhere with this? I am having similar issue with Ionic menus and modals not visible in replays

**Comment by anonimitoraf** [comment]
Just tried it again, but don't see any Replays. Is this because we're on a Free plan (at least I believe we are)?

![image](https://github.com/getsentry/sentry-capacitor/assets/15933322/d7500b8b-d438-4bbf-a406-f134007e1681)

**Comment by bruno-garcia** [comment]
> Just tried it again, but don't see any Replays. Is this because we're on a Free plan (at least I believe we are)?
> 
> ![image](https://user-images.githubusercontent.com/15933322/272511955-d7500b8b-d438-4bbf-a406-f134007e1681.png)

It looks like you're on an old paid plan, is that possible? If so, you can fix that by going to the subscription page and updating your plan. It includes 500 replays for free and _shouldn't_ cost anything more than you're paying.

You can see the stats page here: https://<org-slug>.sentry.io/stats/?dataCategory=replays&project=1&statsPeriod=14d

**Comment by bruno-garcia** [comment]
We've made changes to the replayer too which includes some fixes. Not sure if ti fixes this but since we haven't heared updates
