### ISSUE TITLE
Stacktrace of capacitor-wrapped angular-ivy Sentry on WKWebView provides no references to app

### ISSUE THREAD

**Issue by drakedeatonuk** [getsentry/sentry-capacitor#332]
### Environment

Key dependencies are:
"@ionic/angular": "6.2.8",
"@angular/core": "15.1.5",
"@capacitor/core": "4.6.1",
"@capacitor/ios": "4.6.1",
"@sentry/angular-ivy": "7.41.0",
"@sentry/capacitor": "0.11.2",
"@sentry/integrations": "7.41.0",
"@sentry/webpack-plugin": "^1.20.0",

### Steps to Reproduce

Problem should be visible on any capacitor-wrapped angular-ivy error stacktrace created on Mobile Safari UI/WKWebView.... simply throw a `new Error()` when your application first starts.

### Expected Result

I expected that the stacktrace produced by a capacitor-wrapped angular-ivy instance of Sentry running on Mobile Safari UI/WKWebView would be a useful stacktrace. 

### Actual Result

Instead the stacktrace references NO components or services in my application.

![Screenshot 2023-03-08 at 23 36 56](https://user-images.githubusercontent.com/41165256/223879383-4135b144-bc0a-4990-ab54-360027f46ea0.png)
![Screenshot 2023-03-08 at 23 38 20](https://user-images.githubusercontent.com/41165256/223879404-73967a84-4950-47ab-9f57-274a4f8969e2.png)
![Screenshot 2023-03-08 at 23 38 35](https://user-images.githubusercontent.com/41165256/223879412-b0b18860-d50c-484e-a94d-9b203d714385.png)

I am left wondering if these are simply the stack traces I can expect from this environment...

- The stacktraces I get on Chrome for the same thrown Error are much simpler are include my components/services:
![Screenshot 2023-03-09 at 09 04 33](https://user-images.githubusercontent.com/41165256/223973117-491b6707-357c-4563-a459-a1e0410d725b.png)

- I have set up the source maps & am getting no errors with regards to my configuration. This is my current configuration for reference:

![Screenshot 2023-03-08 at 23 40 48](https://user-images.githubusercontent.com/41165256/223879058-bd8c68ac-bcb6-49eb-863d-90e8dffa9be8.png)
![Screenshot 2023-03-08 at 23 41 24](https://user-images.githubusercontent.com/41165256/223879061-b34c5cb7-5868-4ac6-ada3-c6711c181ffd.png)

- I am uploading the DSYM debug files on every build, along with refreshing the source maps on every build.

-------------------------------------

Not quite sure what I'm missing here. Are these stacktaces normal? Is this a bug with this library? Or with Safari? Does anyone have any advice on how to get better stacktraces in this context?

**Comment by lucas-zimerman** [comment]
Hi and thanks for opening this issue :D 

Just a few questions in advance:
- Does it also happen on Safari from MacOS?
- How are you building/testing  the app ? (for example, I am using this command 'ionic build' to build the app, 'npx cap sync' to update the code on the iOS solution and I am running the app from xcode)

**Comment by drakedeatonuk** [comment]
Hi @lucas-zimerman thanks for your help with this!

Issue is essentially the same on Safari on MacOS

![Screenshot 2023-03-09 at 13 57 08](https://user-images.githubusercontent.com/41165256/224047753-3fe2aa3f-aa02-49c8-8e2c-0d9b6239b331.png)
![Screenshot 2023-03-09 at 13 57 47](https://user-images.githubusercontent.com/41165256/224047778-e823ee22-d9c6-41a1-ad84-8234e47fcf6a.png)

Build process is:
`ng build` (wrapped in the NX cli)
`cap sync`
Also then running the app from Xcode

Assuming you have a similar environment, When you throw a `new Error()` in an app's root component (app.component.ts for me), does your stacktrace include any references to your components?

**Comment by drakedeatonuk** [comment]
FYI this is still an issue! please don't just close this issue 🙏

**Comment by drakedeatonuk** [comment]
To rephrase the problem simply:

In a capacitor-wrapped angular-ivy error stacktrace created on Mobile Safari UI/WKWebView, when I throw a `new Error()`  in my app's root component (app.component.ts for me), the resulting stacktrace on Sentry includes no references to my components.

Can anyone offer some advice on this issue?

**Comment by drakedeatonuk** [comment]
This is still an issue :(

**Comment by jskrepnek** [comment]
@drakedeatonuk One way to resolve this is by configuring zone.js to _not_ wrap unresolved promises.  See https://github.com/angular/angular/pull/35873.

**Comment by drakedeatonuk** [comment]
👀 👀 👀 I will investigate this when I have time in the comings weeks - thanks for the lead!
