### ISSUE TITLE
Requesting release with current sentry javascript

### ISSUE THREAD

**Issue by DavidBowdoin** [getsentry/sentry-capacitor#345]
### Environment

Latest @sentry/capacitor  0.11.2

### Steps to Reproduce

I would like to install:
@sentry/capacitor  (peerDependencies set to 7.37.1)
@sentry/angular-ivy  (a new package and the oldest version is 7.39.0)
@sentry/node

There is no set of versions that I can install that it will accept.

### Expected Result

A release to NPM of the current main branch of https://github.com/getsentry/sentry-capacitor would solve my problem.

### Bonus
can the peerDependencies be set to ^  rather than fixed to a specific version?

**Comment by lucas-zimerman** [comment]
Hi and sorry for the delay since I was in holiday. I'll update the dependencies to the latest version and release a new version with it soon : )

**Comment by mfrey-WELL** [comment]
Any update on this? I would really like to upgrade and use the new features. 🚀

**Comment by lucas-zimerman** [comment]
A new version has been release so I will be closing this issue. If you need anything else feel free to open a new issue  : )
