### ISSUE TITLE
XCode warnings: 'sdkInfo' is deprecated

### ISSUE THREAD

**Issue by piotr-cz** [getsentry/sentry-capacitor#351]
### Environment

@sentry/capacitor: 0.11.2
XCode 14.2

### Steps to Reproduce

Build app with XCode

### Expected Result

No warnings

### Actual Result

XCode logs 2 warnings:

*'sdkInfo' is deprecated. This property will be removed in a future version of the SDK*

With trace to https://github.com/getsentry/sentry-capacitor/blob/021d32a2b77df8372917e97be00f989396596205/ios/Plugin/Plugin.swift#L126-L129

And sentry-cocoa 7.27.1:

https://github.com/getsentry/sentry-cocoa/blob/3441e8f9be290edcc7be57c93a1c128c1a787c2a/Sources/Sentry/Public/SentryOptions.h#L167-L168

**Comment by lucas-zimerman** [comment]
This will be fixed on the next version
