### ISSUE TITLE
Missing yarn prepack step

### ISSUE THREAD

**Issue by borgoat** [getsentry/sentry-capacitor#360]
### Environment

I'm using yarn v3 and importing `@sentry/capacitor` as a Git dependency (this is because I am using my fork). 

### Steps to Reproduce

1. Forked this repo
2. In my package.json dependencies, I now have `"@sentry/capacitor": "borgoat/sentry-capacitor#head=yarn-2"`
3. `yarn install`

### Expected Result

I can still import and use `@sentry/capacitor`, but based on my fork.

### Actual Result

I am not getting a correctly packaged dependency. The `dist` folder is missing, and the library is therefore unusable.

### Proposed Fix

Configure  the `prepack` lifecycle step to perform the library build, instead of `prepublishOnly`. This is the best practice according to Yarn as far as I can tell [^1].

> **Note about `yarn pack`**: Although rarely called directly, `yarn pack` is a crucial part of Yarn. Each time Yarn has to fetch a dependency from a "raw" source (such as a Git repository), it will automatically run `yarn install` and `yarn pack` on it to know which are the files to use.

and also

> [...] the prepublish hook shouldn't have side effects. In particular don't transpile the package sources in prepublish [...]

If you agree, I can provide a quick PR to address this.

[^1]: https://yarnpkg.com/advanced/lifecycle-scripts

**Comment by lucas-zimerman** [comment]
Thank you for pointing out!
As far as I can judge there'll be no side effects to others , since it's a quick fix I opened the PR but feel free to review if you feel like there's anything else that you'd like to see :)

**Comment by borgoat** [comment]
I'm not really sure if that will impact this change or not, but I should mention that I did my tests with yarn 3.5 since we only use that internally. The branch in my fork uses that[^1]. While this repo is still using v1 which has not received much attention lately, maybe it's worth migrating[^2].

[^1]: https://github.com/borgoat/sentry-capacitor/commit/3268416bdf7cac9e393fabd6a4bd1a9e65ec2266
[^2]: https://yarnpkg.com/getting-started/qa#why-should-you-upgrade-to-yarn-modern
