### ISSUE TITLE
Cannot upload separate artifact bundles with different dists

### ISSUE THREAD

**Issue by DGeoWils** [getsentry/sentry-capacitor#361]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I am having an issue with cross platform apps and version ids when uploading sourcemaps via artifact bundles. I am using a separate dist for iOS and Android platforms. This would seem to require a separate artifact bundles tied to each dist.  Unfortunately the first artifact bundle is overwritten by the second. I'm sure I can workaround by using separate version numbers for the android and ios builds, but I would like to avoid that.

Thank you!

1. Create a build with sourcemaps for ios
2. Inject debug_id - `sentry-cli sourcemaps inject ./dist`
3. Upload artifact bundle - `sentry-cli sourcemaps upload --use-artifact-bundle --release=1.0.0 --dist=ios ./dist`
4. Create another build with sourcemaps for android
5. Inject debug_id - `sentry-cli sourcemaps inject ./dist`
6. Upload artifact bundle - `sentry-cli sourcemaps upload --use-artifact-bundle --release=1.0.0 --dist=android ./dist`

### Expected Result

1. Issues created using version 1.0.0 & dist ios will have sourcemaps applied. 
2. Issues created using version 1.0.0 & dist android will have sourcemaps applied. 

### Actual Result

1. Issues created using version 1.0.0 & dist ios do **NOT** have sourcemaps applied. 
2. Issues using version 1.0.0 & dist android do have sourcemaps applied. 
3. No artifact bundle appears in /settings/projects/<project>/source-maps/artifact-bundles/ for version 1.0.0 & dist ios

### Product Area

Releases

**Comment by iambriccardo** [comment]
Hi @DGeoWils, happy to help! Just a quick check. Can you delete the dist folder created by the iOS build after you uploaded it? And then create the folder again for Android.

**Comment by DGeoWils** [comment]
That's what I did -- the `npx ionic cap sync ios --prod --source-map` command deletes the build folder and recreates it

**Comment by iambriccardo** [comment]
Thanks @DGeoWils! I didn't work directly on the `sentry-cli` but from my understanding, the `bundle_id` (an identifier of the bundle) is generated based on its contents (https://github.com/getsentry/sentry-cli/blob/ed8bc1ff6dff3430c235c4cc4da7c124bc528ee5/src/utils/file_upload.rs#L378-L401). If the contents are the same and you upload two times in a row, Sentry will de-duplicate on server side the bundle, by keeping only the latest one, thus resolution for the `ios` one will not work, exactly like in your case.

**Comment by DGeoWils** [comment]
It is certainly possible - that would make my life easier. I had assumed the ios and android bundles would be slightly different, but perhaps ionic/capacitor react to the separate platforms at runtime.

I'll close out this issue and move forward assuming I only need one artifact bundle for both ios and android - and see how that goes.
