### ISSUE TITLE
Bump Sentry JavaScript to 7.51+ for Angular 16 support

### ISSUE THREAD

**Issue by DavidBowdoin** [getsentry/sentry-capacitor#382]
### Environment

Angular 15 (want to move to 16) with Ionic 6

### Desired Result

Update peerDependencies and dependencies to at least 7.51.0 to enable compatibility with the current version of Angular 16.
https://github.com/getsentry/sentry-javascript/releases/tag/7.51.0

### Actual Result

npm ERR! This version of Sentry Capacitor is incompatible with the following installed packages:
npm ERR! @sentry/node version 7.51.0

**Comment by Sampath-Lokuge** [comment]
Any update here, please? i.e. `Angular 16` support.

**Comment by lucas-zimerman** [comment]
Hi, it'll be updated to version 7.54.0

**Comment by Sampath-Lokuge** [comment]
Nice Thanks!
