### ISSUE TITLE
Is there a way to call Sentry.captureException on the native side?

### ISSUE THREAD

**Issue by mlostekk** [getsentry/sentry-capacitor#393]
I am using sentry in a capacitor project, and it is working as expected. The only thing I am wondering is if its possible to also call `Sentry.captureException` on the native side (lets say somewhere in Android native code). 

We are developing a lot of own plugins and extending the native code pretty heavily, so this would be really helpful.

Thanks for any leads.

**Comment by mlostekk** [comment]
No way?

**Comment by lucas-zimerman** [comment]
Since the SDK is bundled with the Native SDKs you can follow the Native documentation of [Android](https://docs.sentry.io/platforms/android/usage/?original_referrer=https%3A%2F%2Fwww.google.com%2F#capturing-errors) or [iOS](https://docs.sentry.io/platforms/apple/guides/ios/usage/?original_referrer=https%3A%2F%2Fwww.google.com%2F#capturing-errors) for capturing errors. Let me know if you need anything else.

**Comment by mlostekk** [comment]
The problem is that I cannot import these files. I have to explicitly add the native Sentry SDK as a dependency in my application's build.gradle file. Is there a trick to access this transitive dependency (app -> capacitor sentry -> native sentry)?

**Comment by mlostekk** [comment]
no trick?

**Comment by bourquep** [comment]
I want to do that as well and can't figure out how...

**Comment by emilianogonzalezar** [comment]
For anyone that needs to do this: you can export Sentry's captureException function through the window and executeJavascript from within the native code:

In Typescript:
```
declare const window: {
  sentry?: any;
} & Window;

window.sentry = { captureException };
```

In native Android Java:
```
public final class Sentry {
    public static void captureException(final Plugin plugin, final String message) {
        new Handler(Looper.getMainLooper()).post(() -> {
            final String script = String.format("window.sentry.captureException(\"%s\");", message);
            plugin.getBridge()
                    .getWebView()
                    .evaluateJavascript(script, null);
        });
    }
}
```

In native iOS Swift:
```
final class Sentry {
  private init() {
  }

  static func captureException(plugin: CAPPlugin, message: String) {
    plugin.webView?.evaluateJavaScript("window.sentry.captureException(\"" + message + "\");");
  }
}
```

You just need to call the Sentry.captureException function from within your plugins.

**Comment by mlostekk** [comment]
Thats smart, but still huge overhead to just track a native exception through the JS layer. I have discarded all capacitor plugins and written my own version with Koin as DI. I think that is a more modern way (Plugins get their implementations injected via Koin, that way testing and invocation from native is super trivial, just thinking of Play Games Auth or Firebase restore being triggered while the JS layer is not even aware that it exists)
