### ISSUE TITLE
Support or documentation for grouping the errors across platforms

### ISSUE THREAD

**Issue by jskrepnek** [getsentry/sentry-capacitor#395]
Hi.  Today, the default issue grouping behaviour results in the equivalent runtime error event on Android and iOS being grouped into different issues, even though the cause is very likely to be the same.

My sense is that grouping equivalent errors across platforms would be a better default behaviour for Capacitor integrations.

So in part I'm requesting this feature for the SDK, but I'm also looking for documentation or guidance for configuring fingerprint rules and stacktrace rules server-side to achieve this without changes to the SDK.

Thanks!

**Comment by lucas-zimerman** [comment]
Thanks for opening this issue!
Right now, are your Stack Traces with or without source maps?

**Comment by jskrepnek** [comment]
> Thanks for opening this issue! Right now, are your Stack Traces with or without source maps?

With

**Comment by jskrepnek** [comment]
Hey, still here waiting for reply

**Comment by bruno-garcia** [comment]
If it's pure JS stack trace, and they look the same. Should group together.

Could you please share a link to two issues you expect grouped together in Sentry?
