### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by mlostekk** [getsentry/sentry-capacitor#437]
### Environment
@sentry/capacitor version 0.12.1

We are having objects with circular references. This leads to the following error

```
y • Uncaught (in promise) TypeError: Converting circular structure to JSON
-> starting at object with constructor 'GameObject' property 'components'
-> object with constructor 'Array'
index 0 -> object with constructor 'SpriteComponent property 'gameObject' closes the circle
at JSON.stringify (<anonymous>)
at eval (wrapper. ts 346:1)
at Array. forEach (<anonymous>)
at Object._serializeObject (wrapper.ts:344:1)
at Object.addBreadcrumb (wrapper. ts: 255:1)
at CapacitorScope. addBreadcrumb (scope.ts: 73:1)
```

The very same code with sentry-javascript works just fine. The problem is caused by this function

https://github.com/getsentry/sentry-capacitor/blob/3c26276ab5f2b3cc20c0eb8a518c678dc6da08d4/src/wrapper.ts#L339

It also looks like `normalizeDepth` is not taken into account, setting it to `1` does not have any effect.

https://github.com/search?q=repo%3Agetsentry%2Fsentry-capacitor%20normalizeDepth&type=code

### Expected Result
It should behave identical to the sentry browser platform. I assume the normalization is not applied when resolving the data objects. Basically sentry should not throw an error when recording an exception with a data object that has circular references.

**Comment by mlostekk** [comment]
Here is a pull request for a possible fix

**Comment by kahest** [comment]
Hey @mlostekk, thanks for reporting and for the PR! We'll have a look and get back to you. cc @lucas-zimerman

**Comment by lucas-zimerman** [comment]
Hi and thanks for the PR @mlostekk! 
Would you like to open a Pull request to the main repo? otherwise I can open one if you prefer.

**Comment by krystofwoldrich** [comment]
In browser JS and RN, we are using the `normalize` function to prevent this.

`normalize` function: https://github.com/getsentry/sentry-react-native/blob/9ee4637908664fd8c5c34d592589352f6112e102/src/js/scope.ts#L62-L67

use in RN SDK: https://github.com/getsentry/sentry-react-native/blob/9ee4637908664fd8c5c34d592589352f6112e102/src/js/scope.ts#L62-L67
