### ISSUE TITLE
Module '"@sentry/angular-ivy"' has no exported member 'BrowserTracing'.

### ISSUE THREAD

**Issue by mariusbolik** [getsentry/sentry-capacitor#441]
Hello,

I am using Version `@sentry/capacitor@0.12.2` with `@sentry/angular-ivy@7.56.0` and I get the following error:

<img width="1230" alt="Bildschirmfoto 2023-08-12 um 14 27 49" src="https://github.com/getsentry/sentry-capacitor/assets/39862171/c9bdb876-9b9f-4812-8af1-3421e6511f92">

It seems like the newer versions of `@sentry/angular-ivy` doesn't have have this typescript error. Can you release a new version of `@sentry/capacitor` that works with a newer version of `@sentry/angular-ivy`?

Kind Regards,
Marius

**Comment by lucas-zimerman** [comment]
Hi and thank you  for opening this issue!

Have you tried using the BrowserTracing from Sentry/Browser?
`import { BrowserTracing } from "@sentry/browser"`

Let me know if that works for you

**Comment by mariusbolik** [comment]
Yes, this works. Thank you!
