### ISSUE TITLE
TypeScript/hybrid layer not implementing new enableWatchdogTerminationTracking setting

### ISSUE THREAD

**Issue by bramosopengov** [getsentry/sentry-capacitor#445]
### Environment

Upgrading from version 0.11.4 to version 0.12.2 of Sentry Capacitor

### Steps to Reproduce

1. Prior to upgrading to v0.12.2, our app implemented a [setting](https://docs.sentry.io/platforms/javascript/guides/capacitor/configuration/options/#enableOutOfMemoryTracking) called `enableOutOfMemoryTracking`
2. This setting is used to disable events sent to Sentry by the native layer if the OS kills the native app on iOS.
3. We are setting it to `false` to disable [out of memory](https://docs.sentry.io/platforms/apple/guides/ios/configuration/out-of-memory/) tracking on iOS.

### Expected Result

We expected setting `enableOutOfMemoryTracking: false` to disable out of memory tracking on iOS.

### Actual Result

Out of memory tracking still occurs on iOS.

It seems this setting was [renamed](https://docs.sentry.io/platforms/apple/guides/ios/configuration/watchdog-terminations/) to `enableWatchdogTerminationTracking` with version 8.0.0 of Sentry Apple SDK. This might be why configuring the setting `enableOutOfMemoryTracking: false` no longer seems to disable it.

**Comment by lucas-zimerman** [comment]
Thank you for opening this Issue and for pointing out a culprit, this should be fixed soon!
