### ISSUE TITLE
Make clear in installation docs that the sibling SDK version has to match.

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-capacitor#45]
We will need to document in the installation steps to ensure the version of the sibling SDK matches the version of the sentry-javascript dependencies that @sentry/capacitor depends on.

**Comment by bruno-garcia** [comment]
Is this something we can verify at build time to warn the user if it's wrong? Documenting is a must, I'm just trying to think of tools we can have to help users go through the: 
* Doesn't work, what's wrong?
* Let me go through the docs see if I find anything, or; raise an issue on GitHub or support

**Comment by lucas-zimerman** [comment]
@bruno-garcia Ideally, We'd need to release a new version of Sentry Capacitor for every release of Sentry Javascript to avoid issues like that

**Comment by lucas-zimerman** [comment]
It seems like the version dependency is being respected if installed using npm, but not with yarn (it'll always install the latest version)
