### ISSUE TITLE
Is the sentry capacitor project well maintained?

### ISSUE THREAD

**Issue by mlostekk** [getsentry/sentry-capacitor#452]
More a generic question. I am seeing quite a lot of problems with the communication with the JS part and the Native processing of the envelopes on multiple versions. (https://github.com/getsentry/sentry-capacitor/issues/450, https://github.com/getsentry/sentry-capacitor/issues/451)

I am wondering if this is a stable project here or do we have something badly maintained? I would like to know earlier than too later and move away from this project at its costing so much time to find out whats wrong. And the more I dig, the more I end up in either the native code processing something incompatible.

Any information about the stability of this project?

**Comment by kahest** [comment]
Hey @mlostekk, thanks for writing in and your concern! We're commited to providing a good experience of course, and we're gonna investigate the issues you created today and follow up there. 👍

**Comment by mlostekk** [comment]
Okay, great to hear. Thanks

**Comment by aparajita** [comment]
@kahest It certainly would give us more confidence in this package if you had the confidence to give it a version >= 1.0.0. Packages with no major version usually mean "not quite ready for prime time". Just saying...

**Comment by mlostekk** [comment]
we have already moved away from this plugin. Too many problems...

**Comment by aparajita** [comment]
> we have already moved away from this plugin. Too many problems...

I also had to give up on it. It was preventing some exceptions from being caught.
