### ISSUE TITLE
Dependency on `sentry-electron` to Set Up Session Replay

### ISSUE THREAD

**Issue by matthew2564** [getsentry/sentry-capacitor#467]
Hi,

I'd like to understand if/why there is a dependency on installing `sentry-electron` to enable `Session Replays` to work as per the docs. (https://docs.sentry.io/platforms/javascript/guides/capacitor/session-replay/?original_referrer=https%3A%2F%2Fstatics.teams.cdn.office.net%2F)

<img width="801" alt="Screenshot 2023-09-20 at 12 30 57" src="https://github.com/getsentry/sentry-capacitor/assets/33056264/dccfbffe-50f7-4a5b-9a6f-e4202198f00e">

I notice with a number of the other SDKs, for example `sentry-react`, there is no mention of the electron package being required.

Thanks

**Comment by bruno-garcia** [comment]
That's a problem on the docs. Thanks for raising, we'll get it fixed

**Comment by matthew2564** [comment]
> That's a problem on the docs. Thanks for raising, we'll get it fixed

Great, thank you 👍🏻
