### ISSUE TITLE
Ionic 6 + Cap 3.x android not compiling

### ISSUE THREAD

**Issue by dgalitsyn** [getsentry/sentry-capacitor#477]
### Environment

I have tried running every version from 0.4.0 to 0.12.1 of the plugin.
The rest of my environment dependencies are as follows:
"@angular/common": "^12.0.0",
"@angular/core": "^12.0.0",
"@capacitor/app": "1.1.1",
"@ionic/angular": "^6.7.5",
"@ionic/cli": "^6.20.1",
"@ionic/core": "^6.7.5",

At the moment I am running these versions of sentry capacitor:
 "@sentry/angular": "7.13.0",
    "@sentry/capacitor": "0.10.1",

Capacitor doctor output:
Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Node:
node -v: v14.18.2
npm -v: 6.14.15

Java: 
We have tried everything from running this with java 1.8, java 11 and java 17.

Android API:
Compile sdk version: 33

### Steps to Reproduce

1. We have upgraded from ionic 5 to 6 in order to solve this issue but also the framework is getting on abit and we needed the upgrade.
2. We have connected an android phone via wireless debugging (can also use an emulator)
3. run npx ionic build
4. run npx cap sync
5. Open Android Studio, run sync gradle and build the app.

### Expected Result

The app running ok I guess.

### Actual Result

As far as I can tell the sentry capacitor plugin never gets the androidx treatment thus failing to compile. I think this is because the plugin is using the old capacitor plugin style with the @NativePlugin annotation instead of the @CapacitorPlugin annotation.
<img width="1894" alt="Screenshot 2023-10-05 at 09 17 53" src="https://github.com/getsentry/sentry-capacitor/assets/36406000/65288fbd-8037-49fa-ad92-728257379b0a">

<img width="1871" alt="Screenshot 2023-10-05 at 09 22 33" src="https://github.com/getsentry/sentry-capacitor/assets/36406000/768af54d-e582-4db4-8f24-0c4bf7c6d4a7">

I think I am doing something wrong here, is there a step I am missing from the setup?

**Comment by lucas-zimerman** [comment]
Hi and thanks for opening the PR, I'll take a look at it and give you an update on what's going on

**Comment by lucas-zimerman** [comment]
I had the same issue when my project was using an old version of Gradle, could you try using a newer version like `com.android.tools.build:gradle:7.2.0` ?
