### ISSUE TITLE
Allow @sentry/angular-ivy@7.77.0 as peer dependency (Angular 17)

### ISSUE THREAD

**Issue by sebsoftpak** [getsentry/sentry-capacitor#508]
### Environment

"@sentry/angular-ivy": "7.77.0",
"@sentry/browser": "7.77.0",
"@sentry/capacitor": "^0.14.0",
"@sentry/tracing": "7.77.0",

### Steps to Reproduce

1. Upgraded the app to Angular 17, NGRX 17, and so on...
2. Upgrade @sentry/ plugins to 7.77.0, the first version "supporting" Angular 17.

### Expected Result

Can't use @sentry/angular-ivy@7.77.0 yet, because of peer dependency issue.
Could you please bump the version in the peer dependencies?
This seems to be the last plug-in preventing us from finishing the upgrade to Angular 17.

### Actual Result

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @sentry/capacitor@0.14.0
npm ERR! Found: @sentry/angular-ivy@7.77.0
npm ERR! node_modules/@sentry/angular-ivy
npm ERR!   @sentry/angular-ivy@"7.77.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @sentry/angular-ivy@"7.73.0" from @sentry/capacitor@0.14.0
npm ERR! node_modules/@sentry/capacitor
npm ERR!   @sentry/capacitor@"^0.14.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @sentry/angular-ivy@7.73.0
npm ERR! node_modules/@sentry/angular-ivy
npm ERR!   peerOptional @sentry/angular-ivy@"7.73.0" from @sentry/capacitor@0.14.0
npm ERR!   node_modules/@sentry/capacitor
npm ERR!     @sentry/capacitor@"^0.14.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by krystofwoldrich** [comment]
Thank you for the message, we made the bump recently it will be released soon.

**Comment by lucas-zimerman** [comment]
Closed as the new version was released.
