### ISSUE TITLE
Use Semver for versioning

### ISSUE THREAD

**Issue by markieo1** [getsentry/sentry-capacitor#519]
All of the Sentry packages follow Semver. 

This is one, doesn't follow Semver. Which means we do not exactly know if there are breakings changes by upgrading. Only by looking at the release notes we might know.

My suggestion is to adjust the versioning to follow Semver, just like all the other Sentry packages do.

**Comment by lucas-zimerman** [comment]
Thanks for opening this issue!

We alter the  the major number here once breakchanges are introduced that impact the end user, the minor for new features and the patch if the version only includes bug fixes

**Comment by lucas-zimerman** [comment]
Feel free to reply if you have any questions
