### ISSUE TITLE
iOS build failing on MacOS with M1 chip

### ISSUE THREAD

**Issue by carlosen14** [getsentry/sentry-capacitor#52]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0

### Steps to Reproduce

1. had my ptoject on a iMac i5, everything worked
2. moved to MBP m1 chip, did a clean npm i, ionic build --platform=ios , npx cap sync ios
3. npx cap open ios
3. tried to build on Simulator, but crashes. but building for a physical device does works!!

### Expected Result

to compile correctly on a simulator

### Actual Result

looks like some libs are missing for this specific arch
![image](https://user-images.githubusercontent.com/9368632/122689747-a3777700-d1ea-11eb-942e-a44eb0859a1c.png)

**Comment by jennmueng** [comment]
@carlosen14 Are you using this SDK from a branch? We don't even support iOS yet and anything in branches we can't guarantee will work. Please upgrade to `0.1.0`.

You can temporarily use the SDK on iOS, albeit without native crash handling by calling init with 
```js
Sentry.init({
  dsn: "___DSN___",
  enableNative: Capacitor.getPlatform() === "android"
})
```

**Comment by phal0r** [comment]
You get this problem, when you make a Release build for a simulator. You can only deploy Debug builds on the Simulator.

**Comment by carlosen14** [comment]
@jennmueng i'll try that way..

**Comment by carlosen14** [comment]
@phal0r i am not launching on release

![image](https://user-images.githubusercontent.com/9368632/122762535-086eb380-d263-11eb-9b0b-12d4045651a7.png)

**Comment by carlosen14** [comment]
i am not sure why i was using version 0.17, which is from 2 years ago, i guess i copied the project including package-lock, i'll try with updated version.

**Comment by carlosen14** [comment]
i tried with version 1.0.0, i get more errors now. 

![image](https://user-images.githubusercontent.com/9368632/122763475-fd685300-d263-11eb-9b6b-f3846aa6f63e.png)

there are my dependencies

```
  "dependencies": {
    "@angular/common": "^10.2.4",
    "@angular/core": "^10.2.4",
    "@angular/forms": "^10.2.4",
    "@angular/platform-browser": "^10.2.4",
    "@angular/platform-browser-dynamic": "^10.2.4",
    "@angular/router": "^10.2.4",
    "@apollo/client": "^3.0.0",
    "@capacitor/android": "^2.4.6",
    "@capacitor/core": "2.4.6",
    "@capacitor/ios": "^2.4.6",
    "@fortawesome/angular-fontawesome": "^0.8.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.34",
    "@fortawesome/free-brands-svg-icons": "^5.15.2",
    "@fortawesome/free-regular-svg-icons": "^5.15.2",
    "@fortawesome/free-solid-svg-icons": "^5.15.2",
    "@ionic-native/core": "^5.0.0",
    "@ionic-super-tabs/angular": "^7.0.8",
    "@ionic-super-tabs/core": "^7.0.8",
    "@ionic/angular": "^5.0.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "apollo-angular": "^2.2.0",
    "conekta-capacitor": "0.0.22",
    "graphql": "^15.0.0",
    "jetifier": "^1.6.6",
    "leaflet": "^1.7.1",
    "lodash": "^4.17.20",
    "marked": "^2.0.3",
    "moment": "^2.29.1",
    "rxjs": "^6.6.3",
    "sentry-cordova": "^1.0.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1000.8",
    "@angular/cli": "^10.2.1",
    "@angular/compiler": "^10.2.4",
    "@angular/compiler-cli": "^10.2.4",
    "@angular/language-service": "^10.2.4",
    "@capacitor/cli": "^2.4.6",
    "@compodoc/compodoc": "^1.1.11",
    "@ionic/angular-toolkit": "^2.3.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/leaflet": "^1.5.21",
    "@types/lodash": "^4.14.168",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "^4.10.0",
    "@typescript-eslint/parser": "^4.10.0",
    "codelyzer": "^6.0.0",
    "ionic-version": "^1.0.3",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "nconf": "^0.11.2",
    "netlify": "^6.1.29",
    "protractor": "~7.0.0",
    "snazzy": "^9.0.0",
    "standard": "^16.0.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  },

```

**Comment by jennmueng** [comment]
@carlosen14 Oh you're using `sentry-cordova` and not `@sentry/capacitor` which this is the repo for. `sentry-cordova` is not designed to work with Capacitor.

**Comment by jennmueng** [comment]
We cannot guarantee that it will work or will be stable on capacitor. However, if you do get it to work then @philipphofmann  would have better insight on that error.
