### ISSUE TITLE
Add Web Vitals support

### ISSUE THREAD

**Issue by thmclellan** [getsentry/sentry-capacitor#561]
Add support to Web Vitals: 

https://docs.sentry.io/product/performance/web-vitals/

We're using Sentry/Capacitor for an Ionic/Angular app that's served to web, iOS, and Android users. 

Related issue with mobile vitals: https://github.com/getsentry/sentry-capacitor/issues/195

**Comment by lucas-zimerman** [comment]
Hi @thmclellan Are not seeing any web vitals on your project? Do you have any navigation transaction being registered on your project?

**Comment by thmclellan** [comment]
Thanks @lucas-zimerman, when I enable browser tracing with   tracesSampleRate: 1.0 and SentryAngular.BrowserTracing() as a new integration, then I see some stats in the Performance tab including navigation transactions, but I don't have a Web Vitals tab. I assumed maybe it wasn't available with sentry-capacitor. Do I need to have Google Analytics vitals tracking in place for Sentry web vitals to work or should it just come automatically? 

In any case feel free to close this issue if Sentry-Capacitor / angular-ivy does include web vitals support, I assumed it was not available yet like mobile vitals.

**Comment by AyushBlueKaktus** [comment]
In my angular application, web vitals is disabled but other "performance" and "insights" tabs are working fine, is it necessary to implement sourcemaps in Sentry to access this feature?
