### ISSUE TITLE
@sentry/vue + @sentry/capacitor - `attachProps`, seems not to passed to Sentry

### ISSUE THREAD

**Issue by agwisniewska** [getsentry/sentry-capacitor#566]
### Environment

What version are you running? Etc.
` "@sentry/vue": "^7.69.0"`
 `"@sentry/capacitor": "^0.15.1"`

### Steps to Reproduce

1. What
3. you
4. did.

I am trying to migrate from using @sentry/vue to @sentry/capacitor
@sentry/vue (current config)
<img width="644" alt="Screenshot 2024-02-06 at 22 34 26" src="https://github.com/getsentry/sentry-capacitor/assets/16926778/ed76c73b-d1f1-4495-b3d6-60b8e02f3708">

@sentry/capacitor (something that I implemented based on the examples 🤔 )
<img width="589" alt="Screenshot 2024-02-06 at 22 33 05" src="https://github.com/getsentry/sentry-capacitor/assets/16926778/fe592dcf-9ef7-4f81-b94f-3239f0f319d4">

### Expected Result

1. with `attachProps: true` props are passed properly to Sentry

_(screenshot of the logs with @sentry/vue)_
<img width="318" alt="Screenshot 2024-02-06 at 22 19 29" src="https://github.com/getsentry/sentry-capacitor/assets/16926778/db527e6e-5bf3-4710-802f-43bf8c9d756f">

@lucas-zimerman do you maybe see any obvious, wrong implementation here? 

### Actual Result

attachProps seems to have no results (no props attached inside sentry.io log report)

###  What actually happened. Maybe a screenshot/recording? Maybe some logs?
as described and presented above. I didn't find any examples of how to do it properly and the current approach seems not to work anymore.

**Comment by lucas-zimerman** [comment]
I am sorry that you are experiencing issues integrating Sentry Capacitor with VUE, we'll investigate what's going on and give out a return shortly
