### ISSUE TITLE
Align in_app from RewriteFrames

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-capacitor#568]
I noticed that there are some differences between the React Native SDK and the Capacitor one.

for instance
[native code] is flagged as true on React Native and false on Capacitor.

we should align the usage of in_app on Capacitor if it should be kept as is or changed to the way React Native is using.

**Comment by kahest** [comment]
Let's find out what the differences are and why they are, then we can decide whether we want to align the behavior
