### ISSUE TITLE
Please support / bump the version to support Capacitor 6

### ISSUE THREAD

**Issue by sebsoftpak** [getsentry/sentry-capacitor#590]
Hi, I'm preparing our apps for Capacitor 6, but it seems @sentry/capacitor is the last keeps me from upgrading it.
Could you please bump the versions, or make the checks more loosely? Had the same problem when Angular 17 came out.
Thanks, Sebastian

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @sentry/capacitor@0.16.0
npm ERR! Found: @capacitor/core@6.0.0-rc.0
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"^6.0.0-rc.0" from the root project
npm ERR!   peer @capacitor/core@"^6.0.0-rc.0" from @capacitor/android@6.0.0-rc.0
npm ERR!   node_modules/@capacitor/android
npm ERR!     @capacitor/android@"^6.0.0-rc.0" from the root project
npm ERR!   7 more (@capacitor/app, @capacitor/camera, @capacitor/device, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@">=3.0.0" from @sentry/capacitor@0.16.0
npm ERR! node_modules/@sentry/capacitor
npm ERR!   @sentry/capacitor@"^0.16.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @capacitor/core@5.7.2
npm ERR! node_modules/@capacitor/core
npm ERR!   peer @capacitor/core@">=3.0.0" from @sentry/capacitor@0.16.0
npm ERR!   node_modules/@sentry/capacitor
npm ERR!     @sentry/capacitor@"^0.16.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by lucas-zimerman** [comment]
Hi, would you mind sharing the dependencies that you are using in your project?

**Comment by sebsoftpak** [comment]
Hi Lucas. Yes, sure, no problem.

npm list
├── @angular-devkit/build-angular@17.2.3
├── @angular-eslint/builder@17.2.1
├── @angular-eslint/eslint-plugin-template@17.2.1
├── @angular-eslint/eslint-plugin@17.2.1
├── @angular-eslint/template-parser@17.2.1
├── @angular/animations@17.2.4
├── @angular/cli@17.2.3
├── @angular/common@17.2.4
├── @angular/compiler-cli@17.2.4
├── @angular/compiler@17.2.4
├── @angular/core@17.2.4
├── @angular/forms@17.2.4
├── @angular/language-service@17.2.4
├── @angular/platform-browser-dynamic@17.2.4
├── @angular/platform-browser@17.2.4
├── @angular/router@17.2.4
├── @capacitor/android@6.0.0-rc.0
├── @capacitor/app@6.0.0-rc.0
├── @capacitor/camera@6.0.0-rc.0
├── @capacitor/cli@6.0.0-rc.0
├── @capacitor/core@6.0.0-rc.0
├── @capacitor/device@6.0.0-rc.0
├── @capacitor/haptics@6.0.0-rc.0
├── @capacitor/ios@6.0.0-rc.0
├── @capacitor/keyboard@6.0.0-rc.0
├── @capacitor/live-updates@0.1.1
├── @capacitor/status-bar@6.0.0-rc.0
├── @fortawesome/angular-fontawesome@0.14.1
├── @fortawesome/fontawesome-svg-core@6.5.1
├── @fortawesome/pro-light-svg-icons@6.5.1
├── @fortawesome/pro-solid-svg-icons@6.5.1
├── @ionic/angular@8.0.0-dev.11709632212.139b6f63
├── @ngrx/data@17.1.1
├── @ngrx/effects@17.1.1
├── @ngrx/entity@17.1.1
├── @ngrx/router-store@17.1.1
├── @ngrx/store-devtools@17.1.1
├── @ngrx/store@17.1.1
├── @ngx-translate/core@15.0.0
├── @sentry/angular-ivy@7.93.0
├── @sentry/browser@7.93.0
├── @sentry/capacitor@0.16.0
├── @sentry/tracing@7.93.0
├── @softpak/frontend-components-ng@3.4.6
├── @softpak/ng-components@4.4.15
├── @types/luxon@3.4.2
├── @types/node@20.11.25
├── @typescript-eslint/eslint-plugin@6.21.0
├── @typescript-eslint/parser@6.21.0
├── autoprefixer@10.4.18
├── eslint-plugin-unused-imports@3.1.0
├── eslint@8.57.0
├── luxon@3.4.4
├── postcss@8.4.35
├── rxjs@7.8.1
├── tailwindcss@3.4.1
├── ts-loader@9.5.1
├── ts-node@10.9.2
├── tslib@2.6.2
├── typescript@5.2.2
├── webpack-bundle-analyzer@4.10.1
├── webpack@5.90.3
└── zone.js@0.14.4
