### ISSUE TITLE
Is offline caching supported in @sentry/capacitor @sentry/vue ?

### ISSUE THREAD

**Issue by mirko77** [getsentry/sentry-capacitor#591]
I would like to know if offline caching is (or will) be available for @sentry/capacitor @sentry/vue

Currently, I have

```

Sentry.init({
        dsn: 'https://xxx',
        enableNative: false,
        transport: Sentry.makeBrowserOfflineTransport(Sentry.makeFetchTransport),
        transportOptions: {
          // see below
        },
        // Set your release version, such as "getsentry@1.0.0"
        release: rootStore.app.name + ' v ' + rootStore.app.version,

        // We recommend adjusting this value in production.
        tracesSampleRate: 1.0,
        // integrations: [
        //   SentrySibling.browserTracingIntegration()
        // ],
        // Set "tracePropagationTargets" to control for which URLs distributed tracing should be enabled
        tracePropagationTargets: [
          'localhost'
        ]
      }, // Forward the init method to the sibling Framework.
        SentrySibling.init
      );

```

which throws

```

TypeError: capacitor_dist_esm.makeBrowserOfflineTransport is not a function

```

If I use @sentry/browser, no error is thrown but no error is sent either when the app is back online, I also tried to restart it.

Any suggestions?

**Comment by lucas-zimerman** [comment]
Hi, which version of Sentry Capacitor and Sentry vue are installed on your project?

You don't want to use the by default the Native SDK has offline caching support.
Is there any reason for not using the disabling the Native SDK?

**Comment by mirko77** [comment]
Thank you for your reply. 

We had to remove sentry due to a memory leak very similar to the one reported here https://github.com/getsentry/sentry-javascript/issues/2957
