### ISSUE TITLE
No way to disable AppHangTracking in @sentry/capacitor

### ISSUE THREAD

**Issue by sinanverve7** [getsentry/sentry-capacitor#594]
Environment

	•	Framework: Capacitor v4
	•	Platform: iOS

Dependencies

	•	@sentry/capacitor: 0.16.0
	•	Sentry/HybridSDK: 8.18.0

Steps to Reproduce

	1)	Initialize Sentry SDK in app.module.ts with enableAppHangTracking set to false to prevent app hanging timeout errors from being reported.
	2)	Observe the reported errors on the Sentry dashboard.

Expected Result

	•	Sentry should not track app hanging errors when enableAppHangTracking is disabled.

Actual Result

	•	App hanging timeout errors are still being reported to the dashboard.

Additional Information

	•	Upon inspecting the TypeScript definition file option.d.ts, it appears that the enableAppHangTracking option is missing from BaseCapacitorOptions.

**Comment by lucas-zimerman** [comment]
Thanks for reporting this! we will track this issue here #596 and it'll be fixed on the next version! 😊
