### ISSUE TITLE
Bump Sentry Javascirpt to 7.105.0

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-capacitor#597]
I am making this issue to track the bump to the latest version of Sentry JavaScript,

**Comment by dmitry-salnikov** [comment]
I'm really looking forward to it. Current peer dependency is 7.93 which has incompatible API with `@sentry/angular@7.107.0` (`replayIntegration` etc.)

**Comment by marshallds** [comment]
Would it be possible to specify `^7.0.0' instead of pinning the versions?
