### ISSUE TITLE
Cannot resolve symbol 'io'

### ISSUE THREAD

**Issue by adnathanail** [getsentry/sentry-capacitor#62]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Capacitor 0.3.0
Angular 6.8.0

### Steps to Reproduce
1. `npm install --save @sentry/capacitor @sentry/angular`
2. `npx cap sync android`
3. Add android specific plugin declaration to `MainActivity.java`

### Expected Result

Android Studio would recognize the library being imported, the app would run and I would be able to report errors to Sentry.

### Actual Result

Android Studio doesn't recognize the library `io.sentry.capacitor.SentryCapacitor`

![image](https://user-images.githubusercontent.com/7809723/125198587-55d6b300-e25a-11eb-8b9a-cbee33ef908c.png)

**Comment by jennmueng** [comment]
Hmm, can you check that after running `npx cap sync` the `SentryCapacitor` files actually show up inside the `/android` directory?

**Comment by adnathanail** [comment]
I don't think it does, but I'm not 100% sure where it would appear

Would it have a folder like these other capacitor plugins?

![image](https://user-images.githubusercontent.com/7809723/127534429-88636457-3b98-4dca-8ecc-bf506e394b5c.png)

I also did a search for `SentryCapacitor` and nothing came up, except this entry in `capacitor.plugins.json`

```
io.sentry.capacitor.SentryCapacitor
```

**Comment by adnathanail** [comment]
@jennmueng Hi is this where the files should have appeared?

**Comment by goforu** [comment]
Ran to the same issue. I have no idea why this happen. 
But I resolve it by taking action **sync project with gradle files** manually.

**Comment by lucas-zimerman** [comment]
Glad you found the solution, since there's no known workaround.
