### ISSUE TITLE
Feat: track app crash and not only js errors

### ISSUE THREAD

**Issue by Aarbel** [getsentry/sentry-capacitor#624]
Hi Sentry teams,

Is that possible to track capacitor app crashes (keeping logs and app details like memory, etc...) with this plugin ? 

Thanks a lot for your help !

**Comment by lucas-zimerman** [comment]
Hi @Aarbel  this SDK also tracks native Crashes and errors

**Comment by Aarbel** [comment]
@lucas-zimerman thanks a lot, do you have any example ? And how to identify native crashes compared to JS errors of the capacitor webview ?

**Comment by lucas-zimerman** [comment]
native Crashes will have the native Stacktrace, for example:
![image](https://github.com/getsentry/sentry-capacitor/assets/8229322/dd422399-326a-4cef-9e5d-2ad090c5a8c8)
You can test on your project by calling `Sentry.nativeCrash();`

**Comment by Aarbel** [comment]
ok wonderful

**Comment by lucas-zimerman** [comment]
Closing this issue since it was answered, feel free to open a new issue if you need any more information.
