### ISSUE TITLE
feat: Update to capacitor 6

### ISSUE THREAD

**Issue by EinfachHans** [getsentry/sentry-capacitor#630]
As Capacitor 6 is officially released, it would be awesome if you can also release a V6 including support for it.

The migration is quite easy via their migration: https://capacitorjs.com/docs/updating/plugins/6-0

**Comment by EinfachHans** [comment]
@lucas-zimerman This is the last plugin that blocks me from updating to v6, anything to share already?

I can also assist with this, but because you don't stick to the capacitor versioning and support multiple capacitor versions at the same time i have problems to do so.

**Comment by lucas-zimerman** [comment]
Hi @EinfachHans and thanks for creating the issue! Support for Capacitor 6 is planned for the next release

**Comment by EinfachHans** [comment]
not stale

**Comment by RobSchilderr** [comment]
What's the status of this issue?

**Comment by lucas-zimerman** [comment]
The support for capacitor 6 was released, if you have more questions, feel free to create a new issue
