### ISSUE TITLE
Sentry.init() with @sentry/react@7.93.0 causes application to hang and not render

### ISSUE THREAD

**Issue by TheQueenIsDead** [getsentry/sentry-capacitor#634]
### Environment

I have loaded my app in a vite dev server, as well as deploying a preview app using a prod build (web) and have had the same bug in Chrome (124.0.6367.91) and Firefox (125.0.2).

I am using ionic with capacitor, backed by react and vite in typescript. The dependecies are as follows, and the package.json at the time of writing this bug can be found on a feature branch of a side-project I'm developing:
https://github.com/TheQueenIsDead/loot-logger/tree/4e66af464d53f43f5ca0a6283d15a603630d77be

package.json
```json
  "dependencies": {
    "@capacitor/core": "5.7.4",
    "@ionic/react": "^7.0.0",
    "@ionic/react-router": "^7.0.0",
    "@sentry/capacitor": "^0.17.0",
    "@sentry/react": "7.93.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router": "^5.3.4",
    "react-router-dom": "^5.3.4",
  },
  "devDependencies": {
    "@capacitor/cli": "5.7.4",
    "@types/react": "^18.0.27",
    "@types/react-dom": "^18.0.10",
    "@vitejs/plugin-react": "^4.0.1",
    "typescript": "^5.1.6",
    "vite": "^5.0.0",
    "vitest": "^0.34.6"
  },
```

### Steps to Reproduce

1. Clone my repository at [this commit](https://github.com/TheQueenIsDead/loot-logger/tree/4e66af464d53f43f5ca0a6283d15a603630d77be)
2. Note that the `app/src/main.tsx` file has the following contents:
```typescript
import * as Sentry from "@sentry/capacitor";
import * as SentryReact from "@sentry/react";
import {BrowserTracing} from "@sentry/react";

Sentry.init({
  dsn: "https://8fe32e4624f58f6e753fe034b5022d81@o4507146805772288.ingest.de.sentry.io/4507146808655952",
  // release: "",
  // dist: "",
  tracesSampleRate: 1,
  integrations: [ new BrowserTracing() ],
  debug: true
}, SentryReact.init);
``` 
4. Run `cd app && npm ci`
5. Run a vite dev server with `npm run dev`

### Expected Result

The main login page would render in sub-second time. This screenshot was generated after commenting out the sentry and sentry-react imports, as well as the init
![image](https://github.com/getsentry/sentry-capacitor/assets/30706552/1a7a0202-ea57-4eb6-8752-15a6c61d6829)

### Actual Result

The sentry debug logs look ok, nothing renders immediately, some components pop up after waiting 30s or so.
![image](https://github.com/getsentry/sentry-capacitor/assets/30706552/59d6741b-1b3f-48ce-822f-5babc92cbdc2)

Here's a Firefox performance capture of the long delay in page load, it seems to indicate that there's deep recursion of some sort when calling `visit`:
![image](https://github.com/getsentry/sentry-capacitor/assets/30706552/fde81bbb-5531-4c0c-8965-1e3393a2d257)

### Potentially related issues
 - https://github.com/getsentry/sentry-javascript/issues/7215

Any help appreciated! Thanks in advance

**Comment by lucas-zimerman** [comment]
Hi @TheQueenIsDead and thank you for the repro!, we'll investigate this and give you an awnser shortly!
By the way, is version 0.15.0 working well for you?

**Comment by TheQueenIsDead** [comment]
Not stale :-)
