### ISSUE TITLE
Unpin @sentry/vue dependency

### ISSUE THREAD

**Issue by Ericlm** [getsentry/sentry-capacitor#639]
When using Sentry in an Ionic App built with Vue, the `@sentry/vue` dependency is pinned to `7.93.0`, which does not allow new features and fixes. Would it be possible to unpin it ? Like `^7.0.0` ?

I know there have been prior discussion [here](https://github.com/getsentry/sentry-capacitor/issues/628) and [here](https://github.com/getsentry/sentry-capacitor/issues/597), but the issues have been closed automatically. I wanted to bring back the subject as it will become (I think) especially important with the [update to Capacitor 6](https://github.com/getsentry/sentry-capacitor/issues/630).

Thank you!

**Comment by lucas-zimerman** [comment]
Hi and thank you for opening this issue!
Due to the complexity of the hybrid SDKs we have opted for keeping the peerDependency fixed.
We will soon bump the VUE SDK to 7.114.0 so hopefully users will have a better time with the Capacitor SDK and Capacitor 6.

**Comment by lucas-zimerman** [comment]
I am closing this as it's not planned to unpin the vue dependency.
