### ISSUE TITLE
Using @sentry/capacitor with Vue results in the @sentry/vue integration not being loaded 

### ISSUE THREAD

**Issue by blefevre** [getsentry/sentry-capacitor#644]
## Problem
The `VueIntegration` is removed by the Capacitor integration as it supplies it's own `defaultIntegration` array here:
https://github.com/getsentry/sentry-capacitor/blob/3ddd6dd47e8666e42c4765ddf323482ee6401560/src/sdk.ts#L44-L50

This overrides the inclusion of the `VueIntegration` in the `defaultIntegration` array of @sentry/vue here:
https://github.com/getsentry/sentry-javascript/blob/9f1975495a5baa4d0f70c43244b3328f72485d54/packages/vue/src/sdk.ts#L25-L26

The result is errors occurring within Vue are not reported to Sentry as Vue's `app.config.errorHandler` is not set.

## Environment

`package.json`:
```json
  "dependencies": {
    "@capacitor/android": "^5.6.0",
    "@capacitor/app": "^5.0.6",
    "@capacitor/app-launcher": "^5.0.7",
    "@capacitor/browser": "^5.1.0",
    "@capacitor/clipboard": "^5.0.7",
    "@capacitor/core": "^5.6.0",
    "@capacitor/device": "^5.0.6",
    "@capacitor/geolocation": "^5.0.6",
    "@capacitor/ios": "^5.6.0",
    "@capacitor/keyboard": "^5.0.8",
    "@capacitor/local-notifications": "^5.0.6",
    "@capacitor/network": "^5.0.7",
    "@capacitor/preferences": "^5.0.7",
    "@capacitor/push-notifications": "^5.1.0",
    "@capacitor/share": "^5.0.6",
    "@capacitor/status-bar": "^5.0.6",
    "@capacitor/toast": "^5.0.7",
    "@sentry/capacitor": "^0.17.0",
    "@sentry/vite-plugin": "^2.16.1",
    "@sentry/vue": "7.93.0",
    "vue": "^3.4.19"
  }
```

`main.ts`:
```typescript
import * as Sentry from "@sentry/capacitor";
import * as SentryVue from "@sentry/vue";
import { createApp } from "vue";

import App from "./App.vue";

const app = createApp(App);

Sentry.init(
  {
    app,
    dsn: import.meta.env.VITE_SENTRY_DSN,
    environment: import.meta.env.VITE_ENVIRONMENT,
  },
  // Forward the init method from @sentry/vue
  SentryVue.init
);

app.mount("#app");
```

## Workaround
The issue can be worked around by manually including the `VueIntegration`:
```typescript
Sentry.init(
  {
    app,
    dsn: import.meta.env.VITE_SENTRY_DSN,
    integrations: [new SentryVue.VueIntegration()],
    environment: import.meta.env.VITE_ENVIRONMENT,
  },
  // Forward the init method from @sentry/vue
  SentryVue.init
);
```

**Comment by lucas-zimerman** [comment]
Thank you for spotting this issue, we will do our best to fix it on the next release!

**Comment by blefevre** [comment]
Hey @lucas-zimerman, I think the bot may have been over-zealous in closing this, I believe the issue is still present.
