### ISSUE TITLE
Vanilla JS + CapacitorJS?

### ISSUE THREAD

**Issue by orestis-z** [getsentry/sentry-capacitor#672]
How to set up CapacitorJS + Sentry when not relying on JS framework such as React, Vue, Angular etc.?

E.g. is there a way to set up `@sentry/capacitor` and `@sentry/browser` and use all available integrations?

**Comment by lucas-zimerman** [comment]
Hi, you should be able to do that by using @sentry/browser, here is a snippet example
```typescript
import * as Sentry from '@sentry/capacitor';
import * as SentryBrowser from '@sentry/browser'


Sentry.init(
  {
    // ...
  },
  SentryBrowser.init,
);
```

In this case you'll only need to install @sentry/capacitor, since @sentry/browser is already bundled with it.

**Comment by orestis-z** [comment]
Sweet that works! Thanks
