### ISSUE TITLE
 Report dropped spans in client reports

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-capacitor#693]
### Description

Meta issue: https://github.com/getsentry/projects/issues/70

```[tasklist]
### Blocked by
- [ ] https://github.com/getsentry/sentry-java/issues/3527
- [ ] https://github.com/getsentry/sentry-cocoa/issues/4156
- [ ] https://github.com/getsentry/sentry-javascript/issues/12727
```

**Comment by krystofwoldrich** [comment]
Requires JS https://github.com/getsentry/sentry-javascript/releases/tag/8.15.0 or newer (https://github.com/getsentry/sentry-javascript/pull/12751)

Or JS https://github.com/getsentry/sentry-javascript/releases/tag/7.119.0

Currently 1.0.0-beta.1 has 8.9.2

**Comment by kahest** [comment]
[1.0.0](https://github.com/getsentry/sentry-capacitor/releases/tag/1.0.0) uses JS 8.27.0 so we should be good
