### ISSUE TITLE
Please tag new release for Cocoa SDK v8.33

### ISSUE THREAD

**Issue by LTKort** [getsentry/sentry-capacitor#715]
In [https://github.com/getsentry/sentry-capacitor/pull/606](https://github.com/getsentry/sentry-capacitor/pull/606) the Cocoa SDK was bumped to v8.33.0, this has been merged. But it is not available in the latest release.

**Comment by lucas-zimerman** [comment]
Thank you for opening this issue, we will bump it on the next weekend.
