### ISSUE TITLE
Can't build with Xcode 16.0

### ISSUE THREAD

**Issue by TarekAlTarshishi** [getsentry/sentry-capacitor#733]
Platform
iOS, iPadOS

Environment
Develop

Installed
CocoaPods

Version
"@sentry/capacitor": "^0.14.0",
"@sentry/angular": "7.73.0",

Xcode Version
16.0

Did it work on previous versions?
15.4

Steps to Reproduce
Install Xcode 16.0
Build the app.
Expected Result
The app builds and runs as in Xcode 15.4.

Actual Result
The process fails with multiple errors in Sentry's SDK. Concretely, the SentryCrashMonitor_CPPException.cpp file.
no type named 'terminate handler' in namespace 'std'

**Comment by kahest** [comment]
@TarekAlTarshishi can you update the SDK to `0.19.0`? This version uses the latest `sentry-cocoa` SDK under the hood and should build correctly with Xcode 16.

**Comment by francocores** [comment]
> [@TarekAlTarshishi](https://github.com/TarekAlTarshishi) can you update the SDK to `0.19.0`? This version uses the latest `sentry-cocoa` SDK under the hood and should build correctly with Xcode 16.

exactly, for me it's working with version 0.19.0, after update I remove the Podfile.lock and execute this command "cd ios/App && pod install --repo-update"

**Comment by edwinhilgersom** [comment]
Thanks 0.19.0 also did the trick for me!
