### ISSUE TITLE
Support for Sentry Javascript 8.x

### ISSUE THREAD

**Issue by vanpyrzericj** [getsentry/sentry-capacitor#736]
According to the Version Support Policy statement on the sentry js repository, support will end for v7 of the SDK at the end of this year. 

Given that we are still locked to `7.114.0`, I am just curious if there are plans to provide support for v8, or if our team should plan to move away from this package and just use the latest version of the JS SDK directly, and worry about the native parts in some other tool.

Thanks!

**Comment by mfrey43** [comment]
They published a [release candidate](https://github.com/getsentry/sentry-capacitor/releases/tag/1.0.0-rc.1) with v8 three weeks ago but no updates since. I'm also curious when the full release will be available.

**Comment by lucas-zimerman** [comment]
The new release is expected for today!
