### ISSUE TITLE
Unexpected CFBundleExecutable Key

### ISSUE THREAD

**Issue by IIxauII** [getsentry/sentry-capacitor#749]
### Environment

Platform:  target iOS
xCode: 15.4
sentry/capacitor: 0.19

Did it work on previous version?
0.14

### Steps to Reproduce

1. Updated sentry/capacitor from 0.14 to 0.19
2.  Build iOS Archive
3. Bundle and Upload iOS Archive (`xcodebuild -exportArchive -archivePath 'somePath' -exportOptionsPlist 'somePath' -allowProvisioningUpdates -allowProvisioningDeviceRegistration`)

### Expected Result

1. Build succeeds
2. Bundle & Upload succeeds

### Actual Result

1. Build iOS Archive succeeds
2. Bundle & Upload fails at Asset validation:

```
Asset validation failed
Unexpected CFBundleExecutable Key. The bundle at 'Payload/App.app/Frameworks/Sentry.framework/Sentry.bundle' does not
contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable
key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider
contacting the developer of the framework for an update to address this issue.
```

**Comment by lucas-zimerman** [comment]
Hi, and thank you for opening this issue!

Before we dive into troubleshooting, have you tried updating your Pod files after upgrading? This might help resolve the issue if it's related to outdated dependencies. You can do this by navigating to the iOS directory and running the following commands:

```bash

cd ios/App
pod install
```

This ensures that all necessary dependencies, including Sentry, are correctly installed and up-to-date. If you've already done this or if the issue persists after trying it, please let us know, and we'll investigate further.

Thanks!

**Comment by IIxauII** [comment]
Thanks @lucas-zimerman for the reply and sorry for getting back to you so late.

I forgot to mention this in the bug report. I have done a 'pod-install' after the npm module update before trying to build + bundle & upload

In the meantime I tried pushing for a capacitor 6 update and in the process also updated sentry/capacitor to v1.0.1 & updated peer dependency Sentry/HybridSDK to 8.33. But I still encounter this same issue when trying to build + bundle & upload.

The steps I have done to try and resolve the issue is:

* cocoapods clear cache for sentry, clear cache for all
* reinstall pods
* clear xCode build folder cache
* delete xCode derived data
* checked xCode "Build Phases" steps - with focus on "Copy Bundle Resources" step to ensure that no "Target App Supports" folder or Info.plist files are present there

but none of these steps have helped me resolve the issue.

---

While researching this topic I have found some examples where repo maintainers closed these kind of error reports due to them being unrelated to the project. I hope this is not the case here, the xCode error message specified to reach out to third party plugin maintainers so that is what I thought would be best.

Thanks in advance for taking a look here and please let me know if I can be of any help

**Comment by IIxauII** [comment]
This is the sentry.bundle that is mentioned in the error message. The top left + top right is from Frameworkds/Sentry. The bottom left + right is from Sentry.bundle inside Frameworks/Sentry

![Image](https://github.com/user-attachments/assets/9620c0eb-de30-4bff-ae5c-f51ddc6a1d7d)

**Comment by lucas-zimerman** [comment]
This issue is being discussed here: https://discord.com/channels/621778831602221064/1298714283424743485
