### ISSUE TITLE
SentryCapacitor is making the Ionic app really slow.

### ISSUE THREAD

**Issue by rahulbalimidi** [getsentry/sentry-capacitor#81]
My application has become really slow after integrating with capacitor sentry sdk . Our app is an Ionic based one which uses capacitor 3 as its native run time . I have done the basic integration looking at the capacitor docs , i see that the events are flowing in to the dashboard , but the sentry initialization is taking lot of time, even after that the entire app has become really slow. i could see that the console is being overwhelmed with capacitor breadcrumbs and events logging.

How to solve this problem.

This is the simple integration codebase i have added to our project ..

setUpSentry(){
    console.log("setting up sentry")
    Sentry.init(
      {
        dsn: "my dsn key",
    
        // Set your release version, such as "getsentry@1.0.0"
        release: "My Project name",

        debug:false,

        maxBreadcrumbs:50,
        // Set your dist version, such as "1"
        dist: "1"
      },
      // Forward the init method from @sentry/angular
      SentryAngular.init
    );

  }

**Comment by bruno-garcia** [comment]
Thanks for validating @Cyral 

Please feel free to reopen if somehow it didn't resolve the issue for you @rahulbalimidi
