### ISSUE TITLE
Source maps not recognized for Android

### ISSUE THREAD

**Issue by michalsisak** [getsentry/sentry-capacitor#88]
### Environment
MacOS, Android 11
Sentry SaaS (sentry.io)

Which SDK and version?
**sentry/angular** - 6.13.2, **sentry/capacitor**: 0.4.0, **Angular**: 11.0.0, **Ionic**: 5.29.0, **Capacitor**: 3.0.1

### Steps to Reproduce

1. `ionic build --prod` - builds the app and creates source maps in `www` folder
2. `sentry-cli releases --org "org_name" --project "project_name"  files "project_name@1.0.2"  upload-sourcemaps ./www -x .js -x .map --validate --verbose --rewrite --strip-common-prefix` - uploads source maps to Sentry
3. `npx cap sync` - copies the build to `android` folder
4. run the app and cause an error
5. check Sentry and see whether source maps were recognized

### Expected Result
I expect the same error on iOS and Android to show the same stack trace. 

### Actual Result
On iOS it works flawlessly. On Android I get an alert: 
`Source code was not found Url | app:///polyfills-es2015.906050c326169a72ef3f.js`.  I can confirm there is a file uploaded with this name for given release. The issue shows the correct release number as well.
When I compare iOS error and the Android one I can only see a difference in `url` paramater:
- iOS - `capacitor://localhost/tabs/today `
- Android - `http://localhost/tabs/today`

I went through data sent to Sentry, inspected frames in stacktrace and can confirm that filenames are the same for both platforms: `app:///polyfills-es2015.906050c326169a72ef3f.js`

I was going through documentation, different Github issues and any StackOverflow thread I could find which gave me few worthwhile theories:
- https://github.com/ionic-team/ionic-framework/issues/16455
- https://github.com/ionic-team/ionic-cli/issues/3802
-  [This solution from ionic team](https://github.com/mhartington/sentry-ng-ionic/blob/67842cb51e5b0433b89b3b12c02faed9a8b58560/src/main.ts#L12-L37) where stacktrace is being modified. Part of Ionic Sentry webinar: [video](https://www.youtube.com/watch?v=iGuqUtHGTj8&t=2702s) 

I apologize if I am doing something wrong or missed something but I got quite stuck. How can I make Sentry to recognize Android stack trace?

**Comment by jennmueng** [comment]
@michalsisak Hmm if you are getting a `Source code was not found` error but the source map is present with the exact URL and release, this could be something on our end. Can you provide the link to the issue on your Sentry dashboard? (The link is private and would require login, so it's safe to post it here)

**Comment by michalsisak** [comment]
@jennmueng thanks for your response. Here is the [link](https://sentry.io/organizations/injurymap/issues/2683958201/?project=3546086&query=is%3Aunresolved) to the issue where stack trace isn't shown

**Comment by luongtu996** [comment]
same issue

**Comment by bruno-garcia** [comment]
is there a github repo we can use as a repro to debug this?

**Comment by luongtu996** [comment]
https://github.com/getsentry/sentry-capacitor/tree/main/example/ionic-angular-v2

All error in tab1 is not recognized

**Comment by jennmueng** [comment]
> https://github.com/getsentry/sentry-capacitor/tree/main/example/ionic-angular-v2
> 
> All error in tab1 is not recognized

how did you upload the sourcemaps?

**Comment by jennmueng** [comment]
@michalsisak Let me pass the link onto a colleague and will get back to you.

**Comment by Sampath-Lokuge** [comment]
I also have the same issue. Please let me the solution. Thanks!

**Comment by albertinad** [comment]
I'm experiencing the same issue. Is there any update on this one?

**Comment by bruno-garcia** [comment]
I wonder if @marandaneto or @AbhiPrasad has seen something like this?

**Comment by Sampath-Lokuge** [comment]
Hi, @bruno-garcia Any solution for this? We cannot use or completely meaningless your plugin due to no TS errors on your dashboard. i.e. it just shows JS errors and we cannot find out the Line numbers and etc. So please provide a working Repo to test that on our side if this is working fine on your apps. I use Ionic/Angular and Capacitor 3+

**Comment by marandaneto** [comment]
> I wonder if @marandaneto or @AbhiPrasad has seen something like this?

Not really, maybe @jennmueng ?

**Comment by kamilogorek** [comment]
Could someone provide a link to an event that's not correctly source mapped in this scenario?

**Comment by michalsisak** [comment]
@kamilogorek [here](https://sentry.io/organizations/injurymap/issues/2883162469/events/22af18115bff4604bcc8808fddacda51/?project=3546086&statsPeriod=14d) you go. (It's a private link, hope you can access it) You can check other events for this error and see that sourcemaps are recognized for iOS and not for Android.

**Comment by kamilogorek** [comment]
@michalsisak your `dist` is set for the event, but not for the uploaded artifacts. `dist` can be somewhat understood as `directories` for artifacts that share the same `release`. Please see: https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#verify-artifact-distribution-value-matches-value-configured-in-your-sdk

**Comment by Sampath-Lokuge** [comment]
Hi @kamilogorek 

It is not working on both iOS and Android. Please see the iOS link here: [Sentry](https://sentry.alertnetworks.net/organizations/an-net/issues/542/?project=10&query=is%3Aunresolved)

**Comment by kamilogorek** [comment]
@Sampath-Lokuge I cannot access your on-premise Sentry instance.

**Comment by michalsisak** [comment]
Thank you @kamilogorek for correctly pointing out the problem! 

A summary of what happened:
Sourcemaps were not recognized for Android while working great with iOS.
The problem was that `dist` (for us it was Android's `versionCode` in `build.gradle`) was not included with uploaded sourcemaps. I am not sure how exactly was `dist` created in the first place since we were not using it in `Sentry.init()`. It was part of Android events but not iOS ones. That's why only Android sourcemaps were not working properly.

The solution is to include `dist` in both `Sentry.init()` and when uploading sourcemaps: `sentry-cli releases files <release_name> upload-sourcemaps ./www --dist <dist>`.
 More info about it: [Sentry Capacitor source maps](https://docs.sentry.io/platforms/javascript/guides/capacitor/#source-maps) and the [link](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#verify-artifact-distribution-value-matches-value-configured-in-your-sdk) from Kamil.

Alternative solution would be not including `dist` at all but I am not quite sure as how to achieve that.

Hopefully it helps someone 
Thank you again. I will close the issue now as my problem has been solved. @Sampath-Lokuge if you are experiencing other problem ( you are mentioning not working both platforms) please open a new issue.
