### ISSUE TITLE
Android: W/OkHttpClient: A connection to <sentry url> was leaked. Did you forget to close a response body?

### ISSUE THREAD

**Issue by phal0r** [getsentry/sentry-capacitor#92]
### Environment

How do you use Sentry?
self-hosted/on-premise

Which SDK and version?
Capacitor latest (0.4.0)

### Steps to Reproduce

1. Start the app with sentry integration
2. according to the integrations, create sentry events
3. at some point this error occurs in logcat

### Expected Result

No warning should be logged by okhttpclient

### Actual Result

The warning is logged to logcat, which indicates a memory leak:
```
W/OkHttpClient: A connection to <sentry url> was leaked. Did you forget to close a response body?
```

**Comment by bruno-garcia** [comment]
Thanks for raising and sorry for the delay.
Where are those warning coming from? We'd need a repro to look into this as this isn't something we've seen before

**Comment by phal0r** [comment]
@bruno-garcia I described all steps in the bug description. I didn't check since then and just occurred in logcat, when logs are transmitted to sentry server.
