### ISSUE TITLE
Cannot find module './definitions' from 'node_modules/@sentry/capacitor/dist/plugin.js'

### ISSUE THREAD

**Issue by MaximMykhailov** [getsentry/sentry-capacitor#93]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
@sentry/capacitor 0.4.0
@sentry/angular 6.11.0

### Steps to Reproduce
Not sure how to reproduce it but we recently updated our app from cordova to capacitor and now we are having troubles with some of unit tests (jest).
Some test suits fail with error:
```
Test suite failed to run

    Cannot find module './definitions' from 'node_modules/@sentry/capacitor/dist/plugin.js'

    Require stack:
      node_modules/@sentry/capacitor/dist/plugin.js
```

### Expected Result

Test should pass

### Actual Result

  ● Test suite failed to run

    Cannot find module './definitions' from 'node_modules/@sentry/capacitor/dist/plugin.js'

    Require stack:
      node_modules/@sentry/capacitor/dist/plugin.js
      src/app/services/logger.service.ts
      src/app/config/error.handler.ts
      src/app/store/session/reducers/auth.reducer.ts
      src/app/store/session/selectors/auth.selectors.ts
      src/app/services/browser.service.ts
      src/app/pages/wizard/components/wizard.component.ts
      src/app/pages/wizard/components/worry-tool/worry-tool-wizard.component.ts
      src/app/pages/wizard/components/worry-tool/worry-tool-wizard.component.spec.ts

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at node_modules/@sentry/capacitor/dist/esm/index.js:4:22
      at Object.<anonymous> (node_modules/@sentry/capacitor/dist/plugin.js:37:2)
<img width="720" alt="Screenshot 2021-10-13 at 15 18 33" src="https://user-images.githubusercontent.com/59620885/137130808-6081fcfc-5cc0-489e-b025-0a41bb62a031.png">

<img width="1792" alt="Screenshot 2021-10-13 at 15 18 52" src="https://user-images.githubusercontent.com/59620885/137130947-af7e1f50-43c2-48b3-9306-404cafe94660.png">

**Comment by jennmueng** [comment]
@MaximMykhailov Are you using typescript? `definitions.ts` is a typescript types file we have, maybe it's getting ignored somehow?
