### ISSUE TITLE
Dependencies outdated: @sentry/angular

### ISSUE THREAD

**Issue by squio** [getsentry/sentry-capacitor#95]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
- @sentry/capacitor@0.4.0
- ionic 5.6
- angular 12

### Steps to Reproduce

1. run `npm outdated`
2. check: @sentry/angular  current:  6.11.0   wanted: 6.13.3 
3. run `npm install @sentry/angular@lates`

### Expected Result

The `npm install ...` or even `npm update` command should update all packages to the "wanted" version 

### Actual Result

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @sentry/capacitor@0.4.0
npm ERR! Found: @sentry/angular@6.13.3
npm ERR! node_modules/@sentry/angular
npm ERR!   @sentry/angular@"6.13.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @sentry/angular@"6.11.0" from @sentry/capacitor@0.4.0
npm ERR! node_modules/@sentry/capacitor
npm ERR!   @sentry/capacitor@"^0.4.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @sentry/angular@6.11.0
npm ERR! node_modules/@sentry/angular
npm ERR!   peerOptional @sentry/angular@"6.11.0" from @sentry/capacitor@0.4.0
npm ERR!   node_modules/@sentry/capacitor
npm ERR!     @sentry/capacitor@"^0.4.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

**Comment by samizarraa** [comment]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @sentry/capacitor@0.4.1
npm ERR! Found: @sentry/angular@6.16.0
npm ERR! node_modules/@sentry/angular
npm ERR!   @sentry/angular@"^6.16.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @sentry/angular@"6.11.0" from @sentry/capacitor@0.4.1

**Comment by lucas-zimerman** [comment]
the mentioned dependency was updated on https://github.com/getsentry/sentry-capacitor/pull/159 and will be available on the next release.
