### ISSUE TITLE
iOS SDK outdated

### ISSUE THREAD

**Issue by squio** [getsentry/sentry-capacitor#96]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
- @sentry/capacitor 0.4.0

### Steps to Reproduce

1. go to Sentry.io
2. view an iOS error report
3. see the warning about the outdated iOS sdk

### Expected Result

Expected to see the current SDK version in the [Podfile](https://github.com/getsentry/sentry-capacitor/blob/main/ios/Podfile) but it isn't

### Actual Result

Warning at the bottom of the report on the website:

> We recommend you update your SDK from sentry.cocoa@v7.1.4 to sentry.cocoa@v7.4.6
> (All sentry packages should be updated and their versions should match)

**Comment by bruno-garcia** [comment]
We need to bump again soon

**Comment by piotr-cz** [comment]
Now the latest version is [7.16.0](https://github.com/getsentry/sentry-cocoa/releases)
