### ISSUE TITLE
Source maps not recognized on Web

### ISSUE THREAD

**Issue by nprail** [getsentry/sentry-capacitor#97]
### Environment

- @sentry/capacitor@0.4.0
- @sentry/angular@6.11.0
- Capacitor 3.2.0
- Angular 12.2.10

### Steps to Reproduce

1. `npx ionic build --prod --source-map`
2. Source maps are stripped from the deployed code
3. `npx sentry-cli releases files ${RELEASE_NAME} upload-sourcemaps www/ --dist ${CI_PIPELINE_IID} --verbose --rewrite --strip-common-prefix`

### Expected Result

Source maps should be recognized on all platforms. 

### Actual Result

Source maps are recognized on iOS and Android but not on web. 

My best guess as to the issue is shown in this screenshot. The source URLs for both native platforms are prefixed with `app:///` while on the web version, they are prefixed with `app:///https://onsite.event1.io/`.

![image](https://user-images.githubusercontent.com/10778661/138303692-8979a871-2ce8-4c8f-94eb-ac16fc560954.png)

![image](https://user-images.githubusercontent.com/10778661/138305559-1e26e35e-54e2-4226-8ec8-2567f9f75365.png)

**Comment by aahlrichs5** [comment]
I was having the same issue in @sentry/capacitor@0.4.2. For a quick workaround fix I replaced each event stacktrace prefix `app:///` with `""`. Although this isn't the ideal solution I hope you are able to get your source maps going for the time being while there isn't a bugfix yet.

**Comment by KevinKelchen** [comment]
This issue might have potentially been fixed in [this commit](https://github.com/getsentry/sentry-capacitor/commit/d2190045174af59f2801b83bb20dbe780912028c) which has just been released in v0.4.3.

We will try it out soon and plan to report back with findings.

**Comment by aahlrichs5** [comment]
After testing out the fix in [this commit](https://github.com/getsentry/sentry-capacitor/commit/d2190045174af59f2801b83bb20dbe780912028c) we came to the conclusion that this issue is fixed. We were able to remove our band aid patch after upgrading to v0.4.3.

**Comment by KevinKelchen** [comment]
Looks good here, too! 👍

Thank you for the fix! 😀
